- kernel/examples/dump-table/Cargo.toml
- kernel/examples/dump-table/src/main.rs
- kernel/src/client/arrow_data.rs
- kernel/src/client/arrow_utils.rs
- kernel/src/client/default/parquet.rs
- kernel/src/client/mod.rs
- kernel/src/client/sync/parquet.rs
- kernel/src/lib.rs
- kernel/src/scan/mod.rs
- kernel/tests/read.rs
This PR adds:
- push schema down into parquet reader
- use the schema to prune to only selected columns
- reorder columns read from parquet files into the order requested by the schema
- allow specifying columns to select in the `dump-table` command
- some tests for the above
Note that for now this only supports specifying root level columns. Nested support is future work.
> Proper reading of parquet columns

- kernel/examples/dump-table/src/main.rs
- kernel/src/client/arrow_expression.rs
- kernel/src/error.rs
When debugging it can be difficult to know where an error occurred if  it is created in numerous places. For example, today if there's an error in expression eval and you run `dump-table`, you might simply see:
```
Error(Arrow(InvalidArgumentError("Incorrect number of arrays for StructArray fields, expected 2 got 3"))
```
But where in the numerous places arrow errors occur did this happen? Tracking this down can be tricky.
It turns out `thiserror` (the crate we use to create our `Error` class) does have support for backtrace capture (see the fourth code-block [here](https://docs.rs/thiserror/latest/thiserror/)). However, it relies on a nightly only api ([provide](https://doc.rust-lang.org/std/error/trait.Error.html#method.provide) which relies on …
> Add backtrace option to errors

- acceptance/Cargo.toml
- acceptance/src/data.rs
- acceptance/src/lib.rs
- acceptance/src/meta.rs
- acceptance/tests/dat_reader.rs
- kernel/src/client/arrow_conversion.rs
- kernel/src/client/arrow_expression.rs
- kernel/src/expressions/scalars.rs
- kernel/src/schema.rs
This PR does two things:
1. Actually read and verify against the dat golden data
2. Add a `TimestampNtz` type so we can at least de-serialize schemas that mention it
adding `timestamp_ntz` is trivial. it's just a new type and copying what we're already doing for timestamp. Obviously more work to be done on the parquet reader to make this "correct".
> Read and verify dat data + initial bit of timestamp_ntz

- kernel/Cargo.toml
- kernel/build.rs
- kernel/src/actions/mod.rs
- kernel/src/client/default/mod.rs
- kernel/src/client/mod.rs
- kernel/src/error.rs
- kernel/src/expressions/mod.rs
- kernel/src/lib.rs
- kernel/src/scan/mod.rs
- kernel/src/schema.rs
- kernel/src/table.rs
This:
* ensures that all modules (at least) have module level docs, and cleans up some other docs.
* makes some things `pub(crate)` and not `pub` if they were only internal, so they don't show up in the docs
* also adds a check if we're running on nightly (which docs.rs _is_), and if so sets [`doc_auto_cfg`](https://doc.rust-lang.org/rustdoc/unstable-features.html#doc_auto_cfg-automatically-generate-doccfg), which will give a nice note for which things require certain features to be enabled. e.g:
It's a bit annoying to have to gate on nightly, but I think it's worth it to make the docs more understandable. 
* tells docs.rs to build our docs with all features enabled
* puts a link to the docs on docs.rs in `Cargo.toml`, which means that'll be linked next time we publish to crates.io
If …
> add a bunch of docs + nightly detection

- kernel/src/client/arrow_utils.rs
- kernel/src/client/default/parquet.rs
- kernel/src/client/sync/parquet.rs
Taking some of the suggestions from https://github.com/delta-incubator/delta-kernel-rs/pull/156/files#r1552305814
This does simplify the generation of the indices and mask. A couple of things I didn't change:
1. still pass  `requested_schema` and `parquet_schema` to `generate_mask`: This is used only as an optimization to determine if we need a mask at all. Since it's a simple length compare, that's faster than building the whole mask when it's not needed
2. Don't use the `requested_schema` as the schema of the new record batch. It appears the way spark writes checkpoints isn't consistent with the protocol spec atm. it marks `minReaderVersion` and `minWriterVersion` as `nullable`, and so we hit a schema miss-match error if we try and do any reordering in metadata queries. I've created …
> simplify masking and reordering of record batches

- ffi/src/lib.rs
- kernel/Cargo.toml
- kernel/src/client/default/filesystem.rs
- kernel/src/client/default/parquet.rs
- kernel/src/error.rs
This is most non-testing code from hackathon. Most code taken from #144. It supports:
1. Reading parquet files from http/https
2. Reading via the `filesystem` interface from http/https
Currently working on how best to test this since we can't have stable urls to read from
> Add support for presigned-url reading to the default client

- kernel/examples/read-table-multi-threaded/README.md
- kernel/examples/read-table-multi-threaded/src/main.rs
- kernel/src/expressions/mod.rs
Add examples and more details the to `README.md` for `read-table-multi-threaded`.
Rust version got updated, so clippy started warning about two new things that I also fixed:
1. An empty doc comment
2. That the `loop` in this example could  be written as a `while let`. This fix changed a lot of indentation, but no actual logic.
> Make the README for the example make more sense

- kernel/src/engine/arrow_expression.rs
- kernel/src/expressions/scalars.rs
- kernel/src/schema.rs
`TimestampNtz` wasn't fully propagated through the code base, and a `match` clause could simplify to use the primitive type constants.
> Clean up primitive types a bit

- acceptance/README.md
- ffi/Cargo.toml
- ffi/cffi-test.c
- ffi/examples/read-table/read_table.c
- ffi/src/lib.rs
- ffi/src/scan.rs
- kernel/Cargo.toml
- kernel/examples/inspect-table/src/main.rs
- kernel/examples/read-table-multi-threaded/src/main.rs
- kernel/src/actions/visitors.rs
- kernel/src/engine/arrow_data.rs
- kernel/src/engine/default/executor.rs
- kernel/src/engine/sync/json.rs
- kernel/src/lib.rs
- kernel/src/scan/file_stream.rs
- kernel/src/scan/state.rs
- kernel/src/snapshot.rs
Renames straggler [table] client references in the code, that escaped https://github.com/delta-incubator/delta-kernel-rs/pull/191.
> Clean up some more old table client references (replace with engine)

- ffi/Cargo.toml
- ffi/cbindgen.toml
- ffi/src/lib.rs
- kernel/src/schema.rs
The main kernel crate can compile without any engine implementations, but the FFI crate was missing some cfg and toml magic.
While we're at it, add a `cbindgen:ignore` directive to kernel's `impl DataType`, in order to suppress cbindgen warnings about the constants defined there.
> Allow FFI to compile with neither default nor sync engine

- kernel/src/actions/deletion_vector.rs
There was a mistake in the protocol wrt. to the old inline example. Based on the spark code and the new example this decodes correctly.
> make inline dvs work right

- .gitignore
- ffi/src/lib.rs
- kernel/src/engine/arrow_conversion.rs
- kernel/src/engine/arrow_expression.rs
- kernel/src/error.rs
- kernel/src/expressions/scalars.rs
- kernel/src/schema.rs
This PR fixes some inconsistencies when handling Timestamp NTZ types and adds some checks, that bounds for devimal128 type are enforced.
maybe in a follow up we may need to investigate how we can best ensure the `timestampNTZ` feature is enabled when the type is encountered.
> fix: timestamp ntz and decimal conversions

- ffi/src/scan.rs
Makes it difficult for engines to use because the visit functions provide a `const`
> `get_from_map` shouldn't take a mut map

- .github/workflows/build.yml
- ffi/.clang-format
- ffi/Makefile
- ffi/README.md
- ffi/cffi-test.c
- ffi/src/lib.rs
Add sync engine cfg option to the ffi. This will allow us to build with local file paths only (mostly useful for testing).
Changed `ffi-test.c` to build both a sync and default engine. It should pass both.
*Note* This is a draft because I can't get the test to build right. For some reason, the codegenned c code isn't defining the `SYNC-ENGINE` flag. Any ideas @nicklan 
This addresses #199
> FFI Sync Engine changes

- acceptance/src/data.rs
- kernel/src/engine/arrow_expression.rs
When we read from a checkpoint, there can be disagreement about the schema we think we've read, and what was actually in the parquet.  This can cause issues when we try and interact with engine data via expressions. For example [here](https://github.com/delta-incubator/delta-kernel-rs/blob/main/kernel/src/scan/log_replay.rs#L219), where we use the "correct" schema and do not mark dvs as nullable. Also, in our arrow_conversions we make assumptions about the names of the fields that mark map keys and values (see [here](https://github.com/delta-incubator/delta-kernel-rs/blob/main/kernel/src/engine/arrow_conversion.rs#L128)), which also causes issues when the actual materialized names are different.
An example error trying to work with a checkpoint file:
```
Arrow(
InvalidArgumentError( …
```
> don't fully enforce matching schema

- ffi/src/lib.rs
- kernel/src/engine/arrow_conversion.rs
- kernel/src/engine/arrow_expression.rs
- kernel/src/error.rs
- kernel/src/expressions/mod.rs
- kernel/src/expressions/scalars.rs
- kernel/src/schema.rs
Add a `Struct` literal type. The short term use is to use it when integrating with delta-rs. Assumption would be it might also come in handy as we develop the write path and need to express partition values.
Looked through the code if we needed to so some additional handling w.r.t. `fileConstantValues`, but that seems to be all in "raw" form as we find in the actions?
> feat: add struct literal

- Cargo.toml
- kernel/examples/read-table-multi-threaded/Cargo.toml
- kernel/examples/read-table-single-threaded/Cargo.toml
- kernel/examples/read-table-single-threaded/src/main.rs
1. Rename `dump-table` -> `read-table-single-threaded`. Matches naming on Java side, and is more descriptive
2. Add `chrono-tz` feature to both examples. This is needed to print timestamps. Previously the examples would fail on the `all-primitive-values` table, but now they can print it out.
3. Add support for reading from s3 to the single threaded example.
> Minor updates to the examples

- kernel/src/engine/arrow_expression.rs
- kernel/src/expressions/mod.rs
- kernel/src/scan/data_skipping.rs
- kernel/src/scan/mod.rs
- kernel/tests/read.rs
This adds support for applying data skipping when the provided filter is a `NOT` or an `IsNull`.
This turned out to be more "fun" than expected.
For `NOT`, things are fairly simple, we just recursively  transform and then invert.
For `IsNull` it's more tricky. We can't just check the value in the stats, because it has different meanings if `tightBounds` is present or not. So there's a more complex set of conditions, but because both the `tightBounds` AND `nullCount` can be `null`, but we ultimately want a boolean, we have to use [`kleene`](https://en.wikipedia.org/wiki/Three-valued_logic) logic.
This required changing the semantics of `and` and `or` in the expression evaluation. 
Have opened #245 and #246 as follow-ups to this work.
> Support unary NOT and IsNull in data skipping

- kernel/Cargo.toml
- kernel/examples/read-table-multi-threaded/src/main.rs
- kernel/src/scan/mod.rs
- kernel/src/scan/state.rs
- kernel/src/schema.rs
This is a pretty straightforward code-munging PR. Please see the [this comment](https://github.com/delta-incubator/delta-kernel-rs/issues/216#issuecomment-2136621176) where I discuss a shortcoming of this changeset.
We are now using a shared thread-safe pointer to reference schemas in global state instead of cloning.
This addresses #216 .
> Changed Schema to SchemaRef for state scanning

- ffi/src/lib.rs
- kernel/src/expressions/scalars.rs
As a follow-up to #231:
Add a `visit_unary` and make a macro for the other literal scalar types. Also adds some missing `From`s to `Scalar`.
Punting on date/timestamp/decimal for now, need to think more on those how we want to pass them.
> Add unary visitors, and most other scalar types to ffi expressions

- Cargo.toml
- acceptance/Cargo.toml
- ffi/Cargo.toml
- kernel/Cargo.toml
- kernel/examples/inspect-table/Cargo.toml
- kernel/examples/read-table-multi-threaded/Cargo.toml
- kernel/examples/read-table-single-threaded/Cargo.toml
- kernel/src/engine/default/filesystem.rs
Required for downstream pyo3 dependency of delta-rs to be updated https://github.com/delta-io/delta-rs/pull/2581/. Also converts the arrow dependencies into workspace deps so all members share it.
> bump arrow to 52.0 and object_store to 0.10.1

- ffi/src/lib.rs
cbindgen doesn't pick up macro'd functions unless we set `parse.expand`. That has its own issues (see #255). For now, just remove the macro.
> Don't use a macro for expression visitor function def

- kernel/src/scan/log_replay.rs
- kernel/tests/read.rs
The data skipping filter can indicate that a file should be included, but then the file could be removed later on, so we need to not assume that the selection vector is false.
The actual fix is just one line, but I realized we weren't really testing the `scan_data` way of doing scans at all. So I've updated the way we do tests in `read.rs` to run all the scans using _both_ `execute` and `get_scan_data` from the `Scan` to ensure that both work.
I added a test that would fail without the fix as well.
> Fix including files that were removed if scan_batch with predicate

- acceptance/src/data.rs
- kernel/src/schema.rs
Handle parsing nested structs in `schemaString`. Setting iceberg compat causes this. Also enable the iceberg_compat_v1 test for dat, since we do now support column mapping.
Closes #253 .
> handle nested struct in schemaString 

- kernel/src/snapshot.rs
In spark delta these stats are long 
https://github.com/delta-io/delta/blob/97439835a4a667ac2ad86ec6054f0e85e8214760/spark/src/main/scala/org/apache/spark/sql/delta/LastCheckpointInfo.scala#L102-L112
see https://github.com/delta-io/delta-rs/pull/2649 for more information
> changed _last_snapshot_ stats to i64

- acceptance/src/data.rs
- ffi/src/scan.rs
- kernel/examples/inspect-table/src/main.rs
- kernel/examples/read-table-multi-threaded/src/main.rs
- kernel/examples/read-table-single-threaded/src/main.rs
- kernel/src/scan/mod.rs
- kernel/src/snapshot.rs
- kernel/tests/dv.rs
- kernel/tests/read.rs
> scan_builder function added to Snapshot 

- kernel/src/scan/mod.rs
From the protocol:
> In name mode, readers must resolve columns in the data files by their physical names as given by the column metadata property delta.columnMapping.physicalName in the Delta schema. Partition values and column level statistics will also be resolved by their physical names. For columns that are not found in the files, nulls need to be returned. Column ids are not used in this mode for resolution purposes.
So we need to map to physical name otherwise we won't find the column. Note the same is true for `id` mode, so this won't break when we add support for that.
> Index the partitionValues map with column's physical name

- acceptance/Cargo.toml
- acceptance/build.rs
- acceptance/src/data.rs
- ffi/tests/read-table-testing/expected-data/basic-partitioned.expected
- Update to the latest version of DAT
- Don't skip any tests
This requires some slight massaging of the expected data. In particular, some of the expected timestamps are in zone `+00:00` which _is_ UTC ([link](https://en.wikipedia.org/wiki/UTC%2B00:00)), so if we find that, we just convert.
This requires going column-by-column and normalizing if needed. 
This also removes the data_type check, since that actually needs to happen after column normalization, and it does already  happen as part of checking if two columns are equal. See [here](https://arrow.apache.org/rust/arrow_data/equal/fn.equal.html).
> Update to dat 0.3

- .github/workflows/build.yml
- kernel/examples/read-table-multi-threaded/src/main.rs
- kernel/src/engine/default/storage.rs
Arrow printing is actually _really_ slow, so for a big table it's useful to be able to just print a few rows and the total count, for testing, or to get a sense of how fast kernel
> Add a --limit option to read-table-multi-threaded

- kernel/src/engine/arrow_conversion.rs
When we read parquet Map types in delta-rs, the data gets read as rootname "key_value" and then the struct type has two  fields "key", "value". We have casting logic that expects this schema, however when we convert our snapshot.schema to an arrow schema, a mismatch happens because kernel is using other field names.
Error when we optimize tables with Map types.
```python
SchemaMismatchError: Could not find column keys
```
Theoretically arrow fields can use whatever names they want, but since we are reading parquet data and therefore getting these RecordBatches with that structure, it would be just much easier to keep the structure of the datatypes consistent between the two.
See parquet docs:
https://github.com/apache/parquet-format/blob/master/LogicalTypes.md#maps
> fix: make Map arrow type consistent with Map parquet type

- CHANGELOG.md
- Cargo.toml
- ffi/Cargo.toml
- kernel/Cargo.toml
- kernel/src/actions/deletion_vector.rs
release `0.3.0` 🚀 
(don't merge for me please, I'll adjust the date in the changelog when I'm actually about to do the release)
> prepare 0.3.0

- kernel/Cargo.toml
We exceeded 10MB limit on crates.io for package size. Exclude golden tests and golden data from publishing to stay under the limit.
new package size:
```
Finished `dev` profile [unoptimized + debuginfo] target(s) in 19.96s
Packaged 112 files, 557.5KiB (120.8KiB compressed)
```
old package size (and error):
```
Finished `dev` profile [unoptimized + debuginfo] target(s) in 22.06s
Packaged 203 files, 13.9MiB (13.0MiB compressed)
Uploading delta_kernel v0.3.0 (/Users/zach.schuermann/dev/delta-kernel-rs/kernel)
error: failed to publish to registry at https://crates.io
Caused by:
the remote server responded with an error (status 413 Payload Too Large): max upload size is: 10485760
```
> exclude golden tests+data when publishing package

- kernel/src/engine/arrow_conversion.rs
- kernel/tests/golden_tables.rs
Changes made:
- Use `element` as list root name, enable a bunch of tests. This matches the [parquet spec](https://github.com/apache/parquet-format/blob/master/LogicalTypes.md#lists)
- Allow sorting by lists if they contain primitives. arrow supports this and then we can test on tables that are all list cols
- make the call to `assert_columns_match` pass things in the expected order.
> Enable some more golden tests

- kernel/src/snapshot.rs
- kernel/tests/golden_tables.rs
Previously, `read_last_checkpoint` would return `Err(<json error>)` if json parsing of the `_last_checkpoint` file failed. This caused the upstream call to fail due to propagation of the error. Instead we now return `None` from `read_last_checkpoint` in this case - similar to what is returned if the `_last_checkpoint` is not found. This allows log replay to continue without the hint and read the table.
Additionally, this unblocks the `corrupted-last-checkpoint-kernel` golden table test.
> fix: allow kernel to read tables with invalid _last_checkpoint

- kernel/src/snapshot.rs
- kernel/tests/golden_tables.rs
Previously, if read_last_checkpoint returned a valid _last_checkpoint hint but the version requested was None (i.e. requesting the lastest version) we would still list_log_files without listing from the checkpoint hint. This change will detect when we have a valid _last_checkpoint and request the latest version and instead list_log_files_with_checkpoint
A side effect, we will get following error when load a table via s3proxy with a lot log files (more than 1000), but the same issue doesn't occur on delta-rs, after some troubleshooting, the error can be fixed by add this line from delta-rs
https://github.com/delta-io/delta-rs/blob/main/crates/core/src/kernel/snapshot/log_segment.rs#L98
```
ObjectStore(
Generic {
store: "S3",
source: ListRequest {
source: Client {
status: 400,
body: Some( …
```
> fix: list log files with checkpoint when version is None

- kernel/src/engine/arrow_conversion.rs
Strings were unnecessarily serded again, which meant the got escaped and this would fail all schema metadata comparisons in delta-rs.
> fix: metadata string conversion

- Cargo.toml
- acceptance/Cargo.toml
- ffi/Cargo.toml
- kernel/Cargo.toml
- kernel/examples/read-table-multi-threaded/Cargo.toml
- kernel/examples/read-table-single-threaded/Cargo.toml
TLDR used [cargo-edit](https://github.com/killercup/cargo-edit) to upgrade dependencies in cargo.tomls and also removed caret in a few places (notably arrow dependency) since it is the default.
```
$ cargo upgrade -i --pinned allow # after install cargo-edit
name                     old req compatible latest new req
====                     ======= ========== ====== =======
arrow                    ^52.0   52.2.0     53.0.0 ^53.0
arrow-arith              ^52.0   52.2.0     53.0.0 ^53.0
arrow-array              ^52.0   52.2.0     53.0.0 ^53.0
arrow-buffer             ^52.0   52.2.0     53.0.0 ^53.0
arrow-cast               ^52.0   52.2.0     53.0.0 ^53.0
arrow-data               ^52.0   52.2.0     53.0.0 ^53.0
arrow-ord                ^52.0   52.2.0     53.0.0 ^53.0
arrow-json …
```
> [chore] update deps, stop using caret

- CHANGELOG.md
- Cargo.toml
- ffi/Cargo.toml
- kernel/Cargo.toml
release 0.3.1 🚀
diff from [0.3.0..main](https://github.com/delta-incubator/delta-kernel-rs/compare/v0.3.0...main)
(don't merge for me please, I'll adjust the date in the changelog when I'm actually about to do the release)
> prepare 0.3.1

- kernel/Cargo.toml
When running cargo-publish the delta_kernel crate failed to compile; needed to add `arrow-buffer` to `arrow-expression` feature.
```
error[E0432]: unresolved import `arrow_buffer`
--> src/engine/arrow_expression.rs:13:5
|
13 | use arrow_buffer::OffsetBuffer;
|     ^^^^^^^^^^^^ use of undeclared crate or module `arrow_buffer`
For more information about this error, try `rustc --explain E0432`.
error: could not compile `delta_kernel` (lib) due to 1 previous error
```
> fix: add arrow-buffer to arrow-expression feature

- kernel/src/engine/arrow_get_data.rs
- kernel/src/engine_data.rs
Currently, the GetData trait implementation for unit type `()` is in arrow_get_data.rs. This makes the trait impl blocked behind either the `default-engine` or `sync-engine` flags. This PR moves the GetData trait implementation to engine_data.rs to make it available without the flags so that it can be used by other engines.
Closes: #315
> Remove feature flag requirement for GetData on ()

- kernel/src/scan/mod.rs
- kernel/src/snapshot.rs
This is a followup to [this PR](https://github.com/delta-incubator/delta-kernel-rs/pull/336) which patches a mistake in the filter. Protocol has a `protocol.minReaderVersion`,  and no `protocol.min_reader_version` field.
This PR also fixes an intermittent test failure caused by repeat initialization of tracing.  This PR changes the `test_scan_data` test to instead use the test_log crate for initializing logs.
> Fix column name for protocol in P&M query

- derive-macros/src/lib.rs
- kernel/src/actions/mod.rs
- kernel/src/actions/schemas.rs
When arrow fixes https://github.com/apache/arrow-rs/issues/6391, our code will start to fail since we don't allow for nulls in partition values, but they can be null.
This adds an annotation that will cause the generated schema to allow null values. We already have the semantics that if value is null on the arrow side, then `materialize` will simply not include it in the final map, so nothing else needs to change.
Tested by:
1. All tests still pass
2. Added a new test for the `add` schema that ensures it sets the `value_contains_null` field to true on the `partitionValues` map.
3. Looking at generated code and noting we get
```rust
HashMap::<
String,
String,
>::get_nullable_container_struct_field("partitionValues"),
```
> Support annotation for nullable values in a container

- acceptance/src/data.rs
- ffi/src/lib.rs
- kernel/src/error.rs
- kernel/src/lib.rs
- kernel/src/path.rs
- kernel/src/snapshot.rs
Today's log path parsing utilities have two weaknesses:
1. Everything is wrapped in `Option` because of the possibility that some path failed to parse. This complicates code that uses it.
2. The parsing is a thin wrapper around Url, which can only exist very temporarily due to borrowed references. This causes repeated parsing.
To solve both problems, rewrite the parsing utilities to take ownership of -- and embed -- the `FileMeta` they are derived from, so they can be instantiated once, passed around as needed, and the metadata extracted easily at the end. Also amp up the unit tests to cover the functionality more completely.
> Clean up and expand log path parsing utilities

- kernel/src/engine/arrow_conversion.rs
- kernel/src/engine/arrow_data.rs
- kernel/src/engine/arrow_expression.rs
- kernel/src/engine/arrow_utils.rs
- kernel/src/expressions/scalars.rs
- kernel/src/scan/data_skipping.rs
- kernel/src/schema.rs
We already have constants like `DataType::LONG` that can avoid boilerplate like `DataType::Primitive(PrimitiveType::Long)`, and such constants can be used in match arms. Update the code to use them.
> [chore] Use primitive type shortcuts in match arms

- kernel/Cargo.toml
- kernel/src/actions/mod.rs
- kernel/src/expressions/scalars.rs
- kernel/src/scan/data_skipping.rs
- kernel/src/scan/log_replay.rs
Turns out we don't use lazy static in many places so potentially removing the dependency is straight forward. Lazy static itself even gives an example from the standard library. 
https://github.com/rust-lang-nursery/lazy-static.rs?tab=readme-ov-file#standard-library
> chore: remove lazy_static in favor of LazyLock

- README.md
- kernel/Cargo.toml
remove sync-engine from default features so there are no features enabled by default. note this will required delta-rs to change their dependency specification to likely turn on `arrow-conversion` feature flag.
> change default features to be none

- acceptance/Cargo.toml
- acceptance/src/data.rs
- kernel/examples/read-table-single-threaded/src/main.rs
- kernel/src/scan/mod.rs
- kernel/src/utils.rs
- kernel/tests/dv.rs
- kernel/tests/golden_tables.rs
- kernel/tests/read.rs
Currently, `scan::execute` computes all `ScanResult`s ahead of time and returns a vector. This PR changes it to return an iterator that lazily fetches scan files, reads parquet data, and applies deletion vectors. This avoids a large upfront performance cost when executing a scan.
Closes: #123
> Make `scan::execute` return a lazy iterator

- kernel/src/path.rs
warnings happened before when we did `cargo t -p delta_kernel`. this PR just uses developer-visibility and adds a few `#[allow(unused)]`/ dead code
```
Compiling delta_kernel v0.3.1 (/Users/zach.schuermann/dev/delta-kernel-rs/kernel)
warning: fields `filename` and `extension` are never read
--> kernel/src/path.rs:45:9
|
43 | struct ParsedLogPath<Location: AsUrl = FileMeta> {
|        ------------- fields in this struct
44 |     pub location: Location,
45 |     pub filename: String,
|         ^^^^^^^^
46 |     pub extension: String,
|         ^^^^^^^^^
|
= note: `ParsedLogPath` has a derived impl for the trait `Debug`, but this is intentionally ignored during dead code analysis
= note: `#[warn(dead_code)]` on by default
warning: method `is_unknown` is never used
--> …
```
> fix 'unreachable' warnings in ParsedLogPath

- .github/workflows/semver-checks.yml
- kernel/src/engine/default/parquet.rs
Adding a check that will run `cargo semver-checks` against each PR. 
This implements a check for PRs that don't bump the crate version. The check will be run between the `HEAD` of the PR and `main`. So any changes introduced in the PR vs main that break semver are picked up, and the PR will be labeled with `breaking-change`.
Currently can't test the actual adding of a label because (probably) the check needs to be in the main repo, rather than in a PR branch, to be allowed to get write access to the repo. 
So sadly to actually test this we'll need to merge and see if it works. (hooray github actions dev workflow)
> Adding cargo semver checks

- .github/workflows/semver-checks.yml
- kernel/src/engine/default/parquet.rs
We actually need to use `pull_request_target`. This is how delta-rs [does it](https://github.com/delta-io/delta-rs/blob/main/.github/workflows/dev_pr.yml) and is also what github support suggests.
We do take a risk that if someone exploits `cargo semver-checks` they could execute code against our repo. That doesn't seem like a high risk.
The check won't run here as in this case we really do need it to be merged to main.
> Fixing semver check

- derive-macros/src/lib.rs
- kernel/examples/inspect-table/src/main.rs
- kernel/examples/read-table-multi-threaded/src/main.rs
- kernel/examples/read-table-single-threaded/src/main.rs
- kernel/src/actions/mod.rs
- kernel/src/engine/arrow_conversion.rs
- kernel/src/engine/arrow_expression.rs
- kernel/src/engine/arrow_utils.rs
- kernel/src/expressions/scalars.rs
- kernel/src/scan/data_skipping.rs
- kernel/src/scan/log_replay.rs
- kernel/src/scan/mod.rs
- kernel/src/schema.rs
- kernel/tests/read.rs
Constructing new `StructType` instances has historically been more verbose than necessary because they require a `Vec<StructField>`. Update the various constructors to accept `impl IntoIterator` instead, and simplify call sites to take advantage.
> [refactor] Make StructType and DataType::struct_type more general

- kernel/src/actions/deletion_vector.rs
- kernel/src/engine/arrow_expression.rs
- kernel/src/engine/default/mod.rs
- kernel/src/engine/sync/json.rs
- kernel/src/expressions/scalars.rs
- kernel/src/scan/mod.rs
ran across a handful of things during transaction implementation. moving those out into a separate PR so we don't pollute the (already large) transaction PR
> misc docs and renames

- kernel/src/engine/arrow_conversion.rs
- kernel/src/scan/data_skipping.rs
- kernel/src/scan/mod.rs
- kernel/src/schema.rs
Proper nested column support will require a recursive schema transformation facility of some kind, because it's no longer enough to simply iterate over the top-level fields of a schema. We need to recurse deeper, and through arbitrary schema elements. Rather than allow adhoc schema transformations to proliferate, we introduce a `SchemaTransform` trait and update column mapping and data skipping code to use it. 
We also introduce a schema depth checker, which not only makes a very nice test article (high code coverage), it can also be used in the future to do an early safety check for untrusted schema objects that can prevent stack overflow (which is near-SIGKILL catastrophic event in rust).
The schema transform trait has two sets of provided methods:
* `transform_xxx` - hook point for …
> Define and use a schema transformation trait

- kernel/src/schema.rs
Change a stray debugging `println!` into a proper `warn!`. Also format a `match` more nicely.
> Missed cleanups from schema transform PR

- NOTICE
- kernel/Cargo.toml
- kernel/src/scan/log_replay.rs
as titled, leftover code we can clean up. and remove dependency on `either`!
> remove log_replay_iter and process_batch in scan::log_replay

- kernel/src/engine/arrow_expression.rs
Three things:
1. The nested column extraction code was overly complex. Simplified.
2. The in-list extraction code was doing redundant nested column extraction. Clean it up.
3. One of the in-list unit tests was claiming to verify IN but actually executed NOT IN. Fix it.
> Fix some issues with arrow expression eval

- kernel/src/engine/default/filesystem.rs
- kernel/src/engine/default/mod.rs
- kernel/src/lib.rs
- kernel/src/snapshot.rs
This ensures that calls to `list_files` are returned sorted if a `LocalFileSystem` `ObjectStore` is used.
It's not clean for a few reasons:
1. We have to materialize the entire iter in order to sort it
2. We can't easily detect if we're local just by using `type_of` or similar. We have a foreign trait object that doesn't have an `as_any` on it, so we can force the reference into an `Any` which would allow us to use [`is`](https://doc.rust-lang.org/std/any/trait.Any.html#method.is), and we can't _add_ an implementation of something like `as_any` because `dyn ObjectStore` isn't `Sized`. So this resorts to `format`ing the object at creation (since `ObjectStore` requires `Display`) and checking if it starts with `LocalFileSystem`....
Adds a test that when using local client things come back …
> Ensure we return a sorted listing when using a local client

- ffi/src/expressions.rs
- kernel/src/actions/deletion_vector.rs
- kernel/src/actions/visitors.rs
- kernel/src/engine/arrow_conversion.rs
- kernel/src/engine/arrow_expression.rs
- kernel/src/engine/arrow_utils.rs
- kernel/src/engine/parquet_stats_skipping/tests.rs
- kernel/src/expressions/mod.rs
- kernel/src/scan/data_skipping.rs
- kernel/src/scan/mod.rs
- kernel/tests/read.rs
Kernel provides quite a few helper methods that make it easier to create expressions, but not all call sites take advantage of them. Fix that.
Also update the various binary operation helpers to accept `impl Into<Expression>` as their RHS arg, which allows further simplifications.
> [Chore] Use helpers to simplify expression handling code

- Cargo.toml
- README.md
- integration-tests/Cargo.toml
- integration-tests/test-all-arrow-versions.sh
This fixes three issues:
1. The integration test was not enabling enough features to actually test arrow enough. Change it so it does
2. The above caught that we actually _don't_ support arrow 52.x because the various `min/max_opt` functions don't exist there. See https://docs.rs/parquet/53.1.0/parquet/file/statistics/struct.ValueStatistics.html#method.max and note the deprecation since 53 note.
3. Parquet depends on object_store. So we _also_ need to be flexible on `object_store`.  Right now I'm locking it to the 0.11 series (the latest).
> actually check arrow. depend on >=53

- derive-macros/src/lib.rs
Replace `panic!` with `to_compiler_error` in macros.
There seem to be no tests for macros, maybe worth adding but probably deserves a separate issue
resolves #348
> [chore] replace panic with .to_compiler_error in macros

- kernel/examples/inspect-table/src/main.rs
- kernel/src/actions/mod.rs
- kernel/src/actions/visitors.rs
- kernel/src/engine/arrow_data.rs
- kernel/src/engine/default/json.rs
- kernel/src/scan/data_skipping.rs
- kernel/src/scan/mod.rs
We have a convenient `get_log_schema()` function for accessing the Delta log schema, but many operations only need to access the `add` column. Replace clunky projection code with something direct and infallible, wrapped up as `get_log_add_schema()`. 
While we're at it, make both functions return `SchemaRef` instead of `Schema`, to reduce the number of deep clones needed (many use sites anyway need an arc).
> Define and use a get_log_add_schema() function

- CHANGELOG.md
- Cargo.toml
- README.md
- ffi/Cargo.toml
- kernel/Cargo.toml
Release 0.4.0 of all crates! rendered [changelog link](https://github.com/delta-incubator/delta-kernel-rs/blob/deb40066aeaf893f0e8c780c3b0fad699c4b7f5e/CHANGELOG.md)
> release 0.4.0!

- ffi/examples/read-table/CMakeLists.txt
- ffi/examples/read-table/arrow.c
- ffi/examples/read-table/read_table.c
- ffi/src/scan.rs
Fix leaks in `read_table`. It now runs cleanly with `-fsanitize=address`.
Some of these are probably footguns in kernel that we should fix. I've also added comments for now in kernel for some places where engine is responsible to free things. We should look at these and see if we can/should move to a callback model so the freeing is not necessary.
The good news is, this didn't find any leaks in kernel itself, just bad c code :)
Fixes #448 
- ffi test ci job doesn't report leaks
- Locally running and observing sanitizer output. Also checked, no more direct leaks reported by `valgrind`
> fix leaks in read_table

- ffi/examples/read-table/arrow.c
- ffi/src/engine_funcs.rs
- ffi/src/expressions/engine.rs
- ffi/src/expressions/kernel.rs
- ffi/src/lib.rs
- ffi/src/scan.rs
- ffi/src/schema.rs
It is easy to create a use-after-free condition when creating kernel string slices from rust strings -- the raw pointers have no lifetime tracking that would allow the compiler to help. Thus, code like this would compile and produce a use-after-free at runtime:
```rust
expects_string_slice(KernelStringSlice::from(&String::from("free me!")))
```
The temporary `String` is freed as soon as `KernelStringSlice::from` returns, and the resulting `KernelStringSlice` is already invalid before `expects_string_slice` receives it. More pernicious cases may not involve any syntactically obvious borrowing:
```rust
expects_string_slice(String::from("free me!").as_str().into())
```
At that point, it's 100% up to the human to recognize the danger and avoid it by materializing the temporary string.
We …
> Safer FFI string slice handling

- kernel/tests/write.rs
parquet file sizes were changing across runs (perhaps from `parquet` crate updates? or something else?) instead of hard-coding the sizes, we now just read the size of the files we just wrote and compare that with what is written in the delta log.
> fix parquet size in write tests

- .github/workflows/build.yml
- ffi/src/handle.rs
- ffi/src/lib.rs
This PR adds a test where we start to use [miri](https://github.com/rust-lang/miri) to make sure we're not doing anything crazy in our FFI. Initially it just tests a couple of things, which already uncovered an issue (see below). We need to add lots more unit tests for the various ffi functions to get miri to validate what we're doing.
This uncovered that the way we were getting pointers in handles was actually unsound. Previously we would do something like:
```rust
let val = ManuallyDrop::new(Box::new(val));
val.as_ref().into()
```
To get the pointer. This is fine, but note that we are converting from `&T` into a `NonNull<T>` here, which is supported in the trait, but marks the memory as `SharedReadOnly` because we don't own the reference.
But to free the memory we use `into_inner()` …
> inital take on some miri support

- ffi/src/scan.rs
- kernel/examples/read-table-multi-threaded/src/main.rs
- kernel/src/engine/arrow_data.rs
- kernel/src/engine/default/json.rs
- kernel/src/engine_data.rs
- kernel/src/scan/data_skipping.rs
- kernel/src/scan/log_replay.rs
- kernel/src/scan/mod.rs
- kernel/src/transaction.rs
- kernel/tests/dv.rs
- kernel/tests/read.rs
Rust uses methods called `len` not `length`, but we currently have `EngineData::length`. Fix it. 
Also add a corresponding `is_empty` method to keep clippy happy.
See above. Name change of public method.
If there are breaking changes, please ensure the `breaking-changes` label gets added by CI, and describe why the changes are needed.
Compilation + unit tests.
> [chore] Rename EngineData::length as EngineData::len

- ffi/examples/visit-expression/expression.h
- ffi/examples/visit-expression/expression_print.h
- ffi/src/expressions/kernel.rs
- ffi/src/test_ffi.rs
- ffi/tests/test-expression-visitor/expected.txt
This PR changes the `Decimal` in `get_testing_kernel_expression` to have a precision larger than the scale, which is a requirement of `Decimal`s. Moreover and the existing behaviour may cause errors in engines that check that `Decimal`s are well-formed.
The child list parameter name in `visit_literal_struct` is renamed to be consistent with the other visitor.
Finally, the printing is patched up in `expression_print.h` to be consistent with the order in the `Decimal` struct.
I ran the visit-expression test suite with the new expected output.
> Fix decimal in `get_testing_kernel_expression` and visitor printing

- kernel/src/engine/default/parquet.rs
little fix to remove our hardcoded `expected_size`
> fix test_write_parquet expected size

- .github/workflows/build.yml
- derive-macros/src/lib.rs
- kernel/src/engine/default/parquet.rs
- kernel/src/expressions/column_names.rs
- kernel/src/transaction.rs
New CI job called `docs` which will effectively just runs `RUSTDOCFLAGS=-Dwarnings cargo doc` to check for broken docs/links/etc.
Also fixes docs issues to make the new job green :)
> add cargo docs build in CI

- Cargo.toml
- kernel/Cargo.toml
- kernel/src/engine/default/filesystem.rs
- kernel/src/snapshot.rs
- kernel/tests/read.rs
- test-utils/Cargo.toml
- test-utils/src/lib.rs
Move some useful common utils for building an in-memory delta table into their own crate.
I want to start adding tests for actually reading data to the `ffi` crate. To do so we need to use an `InMemory` object store, because all i/o in tokio fails in miri due to it using epoll, which miri doesn't support. So we'll need to build in-memory tables and use the `memory:///` url to get a memory backed `ObjectStore`. 
We already do this in `read.rs` in kernel, but there's no way to get at that code inside the ffi crate. So this moves a bunch of utilities for this sort of thing into its own "test-utils" crate and uses it in read.rs.
I've also cleaned up and renamed things a bit. Most of the code remains unchanged.
Follow-up PR(s) will use this in the ffi crate to test more.
Existing tests pass
> Move some common test-utils to their own crate

- kernel/src/engine/arrow_data.rs
- kernel/src/engine/arrow_expression.rs
- kernel/src/engine_data.rs
- kernel/src/lib.rs
As part of implementing various kernel operations, engines need the ability to downcast kernel engine traits to their true concrete types. The rust `Any` trait can help with struct downcasting, but it isn't quite strong enough once traits are involved. For example, given `trait Foo: Any + Send + Sync`, and `struct Bar` that implements `Foo`, the following fails to compile:
```rust
let f: Arc<dyn Foo> = Arc::new(Bar);
let f: Arc<Bar> = f.downcast().unwrap(); // `Arc::downcast` method not found 
```
... as does this:
```rust
let f: Arc<Foo> = Arc::new(Foo{});
let a: Arc<dyn Any + Send + Sync> = f; // trait upcasting coercion is not stable rust
let f: Arc<Foo> = a.downcast().unwrap();
```
We solve the trait downcasting problem with a new `trait AsAny: Any + Send + Sync` -- automatically …
> Define and use new AsAny trait

- kernel/src/path.rs
This PR adds explicit boundary test cases to existing tests:
1. In test_uuid_checkpoint_patterns:
- Tests UUID with exactly 35 characters (one too short)
- Uses realistic UUID format: "3a0d65cd-4056-49b8-937b-95f9e3ee90e"
2. In test_unknown_invalid_patterns:
- Tests file with no extension (returns Ok(None))
- Tests file with empty extension "." (returns Ok(Some) with Unknown type)
> Add boundary test cases for UUID length and file extensions

- CHANGELOG.md
- Cargo.toml
- README.md
- acceptance/build.rs
- ffi/src/expressions/kernel.rs
- kernel/src/engine/parquet_row_group_skipping.rs
- kernel/src/expressions/scalars.rs
- kernel/src/lib.rs
- kernel/src/log_segment/tests.rs
- kernel/src/scan/mod.rs
- kernel/tests/read.rs
Horray for graduating to `delta-io`! But now it's time to update all our stale links :) most are just in `CHANGELOG.md`. Despite most (all?) of them working it seems better to go ahead and normalize everything to the new home.
> replace 'delta-incubator' with 'delta-io'

- kernel/src/scan/mod.rs
- kernel/src/snapshot.rs
previously, we were only checking `protocol.ensure_read_supported()` when we create a `Scan`, instead we should move it up earlier to `Snapshot` creation. this is useful so that we can fail earlier and generally as soon as we get a `Protocol` we should ensure read is supported instead of waiting for `Scan` creation. note this is useful for CDF too (as it relies on snapshots but separate scans)
> move `ensure_read_supported` from `Scan` to `Snapshot`

- kernel/examples/inspect-table/src/main.rs
- kernel/src/actions/mod.rs
The inspect-table example was brittle -- sensitive to field order and requiring a lot of manual fiddlery to add a new action -- and did not have support for the Cdc action.
Rework the code to be simpler and more flexible, and take advantage of that to add Cdc support.
Ran it on a table.
> Clean up inspect-table and add Cdc action support

- kernel/src/table_changes/mod.rs
- kernel/src/table_properties/deserialize.rs
use `TableProperties` for CDF enablement check in `TableChanges`. some minor nits/cleanup in table properties
existing UT
> use TableProperties for CDF check

- CHANGELOG.md
added current unreleased changes before `0.5.0` release (separate PR with hopefully a bit of automation)
view [rendered](https://github.com/zachschuermann/delta-kernel-rs/blob/d2211ff9158f9c8f185d453d818f4bacda8fec55/CHANGELOG.md)
> update CHANGELOG with current unreleased changes

- acceptance/src/data.rs
- kernel/examples/read-table-single-threaded/src/main.rs
- kernel/src/scan/mod.rs
- kernel/tests/common/mod.rs
- kernel/tests/dv.rs
- kernel/tests/golden_tables.rs
- kernel/tests/read.rs
- kernel/tests/write.rs
A previous change made `Scan::execute` return a lazy iterator instead of a collection, but in doing so it captured a `&dyn Engine` which limits the lifetime of the iterator. This is silly, given that the caller has access to an `Arc<dyn Engine>` precisely to avoid lifetime problems. 
Update the method to take an Arc and fix the compiler carnage that results.
Fixes https://github.com/delta-io/delta-kernel-rs/issues/551
`Scan::execute` is public, as are some of the impacted methods that rely on it.
Compilation suffices (yay for rust borrow checker!)
> Scan::execute takes an Arc<dyn EngineData> now

- acceptance/src/data.rs
- acceptance/tests/dat_reader.rs
- kernel/src/actions/mod.rs
- kernel/src/actions/visitors.rs
- kernel/src/engine/arrow_data.rs
- kernel/src/engine_data.rs
- kernel/src/scan/mod.rs
- kernel/src/scan/state.rs
- kernel/src/schema.rs
- kernel/src/snapshot.rs
- kernel/src/table_changes/mod.rs
- kernel/src/table_changes/scan.rs
- kernel/src/table_features/column_mapping.rs
- kernel/src/table_features/mod.rs
Today's code scatters column mapping validity checks around the various use sites which makes them complex and requires propagating the column mapping mode through various function calls.
We can simplify by validating the schema once, up front during snapshot load. In particular:
1. Ensure that (correct) column mapping annotations are present in the schema exactly and only when column mapping is actually enabled. This simplifies logical -> physical name translation because we should use the annotation if present and use the field's logical name otherwise.
2. Reject column mapping ID mode early. Most code only needs to care whether column mapping is enabled at all.
As a result, most column mapping operations become infallible and with simpler code. 
`StructField::physical_name` no longer …
> Simplify column mapping mode handling

- README.md
- kernel/src/lib.rs
> chore: update readme for write support

- kernel/src/table_features/column_mapping.rs
previously I accidentally changed default from `None` to `Name`. Instead of simply reverting, this removes `Default` from column mapping entirely.
> fix: remove column mapping default

- .github/workflows/build.yml
- ffi/Cargo.toml
- ffi/examples/read-table/README.md
- ffi/examples/read-table/read_table.c
- ffi/src/ffi_tracing.rs
- ffi/src/handle.rs
- ffi/src/lib.rs
This PR provides 3 ways for engines to hook into our logging:
1. getting a struct `Event` type with relevant information that they can format
2. A very simple call that will just pick some defaults and give them a string
3. A slightly more complex one that lets them control the string formatting a little, but still ultimately just hands over a string
Note that the `Compact` format seems a bit broken upstream. I've filled https://github.com/tokio-rs/tracing/issues/3157 for that.
Adds 3 new public ffi APIs
Running in `read_table`, and unit tests
> Enable relaying log events via FFI

- kernel/src/engine/default/filesystem.rs
- kernel/src/engine/sync/fs_client.rs
- kernel/src/lib.rs
This PR fixes the `list_from` method used by both the `DefaultEngine` and the `SyncEngine` to return the correct `FileMeta` struct. Previously, both the engines would return the timestamp in number of seconds from Unix Epoch. However, `FileMeta` specifies that we should expect the modification time to be in milliseconds since Unix Epoch:
```
pub struct FileMeta {
/// The fully qualified path to the object
pub location: Url,
/// The last modified time as milliseconds since unix epoch
pub last_modified: i64,
/// The size in bytes of the object
pub size: usize,
}
```
This changes the behaviour of the following:
- `SyncFilesystemClient::list_from`
- `ObjectStoreFileSystemClient::list_from`
- any transitive users of these methods
I compare the `FileMeta` returned by each of the engines to …
> Engines now return FileMeta with correct millisecond timestamps

- kernel/src/scan/state.rs
- kernel/src/table_changes/log_replay.rs
- kernel/src/table_changes/mod.rs
- kernel/src/table_changes/scan_file.rs
This PR introduces four concepts:
- `cdf_scan_row_schema`: This is the schema that engine data will be transformed into at the end of the log replay phase. This schema prunes the log schema down only to the fields necessary to produce CDF columns. 
- `cdf_scan_row_expression`: This is a function that generates an expression to transform an engine data into the `cdf_scan_row_schema`. The function takes timestamp and commit number as arguments because it inserts these as columns into the output engine data.
- `CDFScanFile`: This is a type that holds all the information needed to read a data file and generate its CDF rows. It holds path, deletion vector, the type of action, and the paired remove deletion vector. The action type is encoded as an enum `CDFScanFileType`
- `CDFScanFileVisitor`: …
> ScanFile expression and visitor for CDF

- ffi/src/scan.rs
- kernel/examples/read-table-multi-threaded/src/main.rs
- kernel/src/scan/mod.rs
- kernel/src/scan/state.rs
- kernel/src/table_changes/scan.rs
- kernel/tests/read.rs
Currently, `Scan::execute` takes the lifetime of the `Scan` into the Iterator, forcing it to live as long as the scan.  This Pr removes that requirement so that the user can lazily consume the iterator without managing the lifetime of `Scan`. This simplifies the usage of kernel 
This PR also changes all `read_schema` names to `physical_schema` to make it clear and consistent what the schema represents. note that `Snapshot` already calls this the `physical_schema`
`Scan::execute` no longer depends on the lifetime of `&self`
Everything compiles :)
> Remove lifetime requirement on `Scan::execute`

- kernel/src/table_changes/scan.rs
This PR adds a pub method to fetch the logical schema of a `TableChangesScan`
Everything compiles.
> Add `TableChangesScan::schema` method to get logical schema

- .github/workflows/build.yml
- kernel/src/engine/default/filesystem.rs
- kernel/src/engine/sync/fs_client.rs
- test-utils/src/lib.rs
- create an abs_diff function in test_utils (same code as in std)
- use that in the two places we wanted it instead
- also add a workflow to make sure that we can always compile against msrv
- Existing tests pass
- New workflow passes
> don't use std abs_diff, put it in test_utils instead, run tests with msrv in action

- .github/workflows/build.yml
title. Introducing since this would have caught the 0.6.0 release blocker. (`engine` code used in `parquet_stats_skipping` module)
> [chore] add CI step to build kernel with no-default-features

- .github/workflows/build.yml
- kernel/Cargo.toml
`hdfs-native` depends on `which` which depends on `home`. `home` recently updated and bumped their msrv to 1.81. This pins us to the previous version.
Check that the msrv test now passes
> Fix msrv check by pinning `home` dependency

- ffi/tests/invalid-handle-code/not-send.stderr
- ffi/tests/invalid-handle-code/shared-not-sync.stderr
New rustc has slightly different error messages. 
tests pass
> fix stderr output for handle tests

- CHANGELOG.md
- Cargo.toml
- README.md
- cliff.toml
- ffi/Cargo.toml
- kernel/Cargo.toml
- release.sh
> release 0.6.1

- release.sh
release script publishing fixes
> fix: release script publishing fixes

- kernel/src/actions/mod.rs
- kernel/src/actions/visitors.rs
- kernel/src/schema.rs
- kernel/src/table_changes/log_replay/tests.rs
1. This PR updates `RemoveVisitor` to read `partition_values`
2. This PR removes the stray break in the implementation of `RowVisitor` for `RemoveVisitor` which prevented reading multiple `Remove` actions in a commit
- Introduced test to parse the `partition_values` field from `Remove` actions
> feat: read `partition_values` in `RemoveVisitor` and remove `break` in `RowVisitor` for `RemoveVisitor`

- ffi/src/test_ffi.rs
- integration-tests/src/main.rs
- kernel/src/actions/mod.rs
- kernel/src/actions/schemas.rs
- kernel/src/engine/arrow_conversion.rs
- kernel/src/engine/arrow_utils.rs
- kernel/src/engine/ensure_data_types.rs
- kernel/src/scan/data_skipping.rs
- kernel/src/scan/log_replay.rs
- kernel/src/scan/mod.rs
- kernel/src/schema.rs
- kernel/src/table_changes/log_replay/tests.rs
- kernel/src/table_changes/mod.rs
- kernel/src/table_changes/physical_to_logical.rs
- kernel/src/table_changes/scan.rs
- kernel/src/table_changes/scan_file.rs
- kernel/src/transaction.rs
- kernel/tests/write.rs
A lot of code (especially in tests) calls `StructField::new` with literal values of the `nullable: bool` argument. Booleans are easy to misinterpret (which value means non-null field?) -- and it's hard to read when the third arg is split to its own line in nested expressions such as:
```rust
StructField::new(
"fileConstantValues",
StructType::new([StructField::new(
"partitionValues",
MapType::new(DataType::STRING, DataType::STRING, true),
false,
)]),
true,
),
```
To improve readability and make the code less error-prone, define two new helper methods/constructors for `StructField`: `nullable` and `not_null`, which create struct fields having the corresponding nullability. 
No new functionality, and all existing unit tests still pass.
To minimize the risk of unfaithful refactoring, the …
> refactor: Make [non] nullable struct fields easier to create

- kernel/src/expressions/mod.rs
- kernel/src/predicates/mod.rs
- kernel/src/predicates/parquet_stats_skipping/tests.rs
- kernel/src/predicates/tests.rs
- kernel/src/scan/data_skipping.rs
- kernel/src/scan/data_skipping/tests.rs
- kernel/src/scan/mod.rs
The first attempt at generalizing SQL was incomplete, supporting only AND/OR and binary comparisons. We can also support NULL literal expressions, boolean column expressions and NOT, so add them. 
Adjusted existing unit tests for the new support (they previously expected it to not work)
> feat: Support NOT and column expressions in eval_sql_where

- ffi/examples/read-table/schema.h
- ffi/src/scan.rs
- ffi/src/schema.rs
- new feature PR: "Expose metadata in SchemaEngineVisitor ffi api"
A new argument "metadata" was added to EngineSchemaVisitor visitor functions.
`examples/read_table` was updated to test the change.
> feat!(ffi): expose metadata in SchemaEngineVisitor ffi api

- ffi/examples/read-table/arrow.c
- ffi/examples/read-table/read_table.c
- ffi/src/scan.rs
- kernel/examples/inspect-table/src/main.rs
- kernel/examples/read-table-multi-threaded/src/main.rs
- kernel/src/scan/log_replay.rs
- kernel/src/scan/mod.rs
- kernel/src/scan/state.rs
- kernel/tests/read.rs
Propagate the computed transforms from #607 through calls to `visit_scan_files`.
> Part 2: propagate transform in visit_scan_files

- kernel/Cargo.toml
- kernel/src/expressions/scalars.rs
- kernel/src/predicates/tests.rs
We currently have a custom implementation for `Scalar::partial_cmp` whith correct NULL semantics. The current derived `PartialEq` implementation is inconsistent with that impl. This PR then introduces a custom implementation for `PartialEq` which uses the `PartialOrd` implementation.
We also extend the implementation of `PartialOrd` to cover decimals via the `bigdecimals` crate, which handles arbitrary precision decimals.
added tests for null handling in `PartialEq` / `PartialOrd`. Decimal comparisons are well covered in predicate tests, where they were previously disabled.
> fix: consistent PartialEq for Scalar

- kernel/src/engine/arrow_data.rs
- kernel/src/engine/ensure_data_types.rs
- kernel/src/engine/mod.rs
- kernel/src/engine/parquet_row_group_skipping.rs
- kernel/src/engine/parquet_row_group_skipping/tests.rs
- kernel/src/predicates/tests.rs
- kernel/src/schema/compare.rs
Apparently `cargo fmt` does not work on modules defined in macros, which we were doing in some places. I don't think this fixes all the misses we have been seeing with `cargo fmt`, but should fix some of them.
just formatting existing code.
> fix: cargo fmt does not handle mods defined in macros

- kernel/src/engine/arrow_data.rs
- kernel/src/engine/arrow_utils.rs
- kernel/src/engine/default/parquet.rs
- kernel/src/engine/sync/parquet.rs
Starting in arrow-53.3, the parquet reader no longer computes NULL masks for non-nullable leaf columns -- even if they have nullable ancestors. This breaks row visitors, who rely on each leaf column to have a fully accurate NULL mask.
The quick-fix solution is to manually fixup the null masks of every `RecordBatch` that comes from the parquet reader. 
Fixes https://github.com/delta-io/delta-kernel-rs/issues/691
New unit test that checks whether parquet reads produce properly nested NULL masks. The test also leverages (and verifies) the JSON parser, so we can reliably detect any unwelcome behavior changes to JSON parsing that might land in the future.
> fix: Ensure properly nested null masks for parquet reads

- kernel/src/scan/data_skipping.rs
- kernel/tests/read.rs
- test-utils/src/lib.rs
Fixes #698
Updates the `DataSkippingFilter` to treat all columns as nullable for the purpose of parsing stats, as suggested in https://github.com/delta-io/delta-kernel-rs/issues/698#issuecomment-2658229733.
This is particularly important for partition columns, which won't have values present in stats. But stats are also only usually stored for the first 32 columns, so we shouldn't rely on stats being present for non-partition fields either.
I've added a new unit test.
I've also tested building duckdb-delta with this change (cherry-picked onto 0.6.1) and verified that the code in #698 now works.
> fix: Handle predicates on non-nullable columns without stats

- ffi/examples/read-table/schema.h
- ffi/src/schema.rs
When given a schema (e.g. in `global_scan_state`) the engine needs a way to visit this schema. This introduces a new API `visit_schema` to allow engines to visit any schema over FFI. An API called `visit_schema` previously existed but visited the schema of a given _snapshot_; this has now been renamed to `visit_snapshot_schema`.
Renamed `visit_schema` to `visit_snapshot_schema` and now `visit_schema` takes `SharedSchema` as an argument instead of a snapshot.
updated read_table test
> feat!(ffi): new visit_schema FFI and rename old visit_schema to visit_snapshot_schema

- kernel/src/actions/mod.rs
- kernel/tests/write.rs
Our previous check was too strict. Now we just ensure that the protocol makes sense given what features are present/specified.
Made all existing `write.rs` tests also write to a protocol 1/1 table, and they all work.
> feat: Support writing to not only 3/7 protocol

- ffi/examples/read-table/arrow.c
- ffi/examples/read-table/arrow.h
- ffi/examples/read-table/read_table.c
- ffi/examples/read-table/read_table.h
- ffi/src/engine_funcs.rs
- ffi/src/expressions/kernel.rs
- ffi/src/lib.rs
- ffi/src/scan.rs
- ffi/tests/read-table-testing/expected-data/basic-partitioned.expected
- kernel/src/engine/arrow_expression.rs
Use new transform functionality to transform data over FFI.  This lets us get rid of all the gross partition adding code in c :)
In particular: 
- remove `add_partition_columns` in `arrow.c`, we don't need it anymore
- expose ffi methods to get an expression evaluator and evaluate an expression from `c`
- use the above to add an `apply_transform` function in `arrow.c`
- existing tests
> Part 4: read_table.c uses transform in ffi

- ffi/examples/read-table/read_table.c
- ffi/examples/read-table/schema.h
- ffi/src/engine_funcs.rs
- ffi/src/lib.rs
- ffi/src/scan.rs
- ffi/src/schema.rs
- kernel/src/snapshot.rs
This PR removes the old `visit_snapshot_schema` introduced in #683 - we should just go ahead and do the 'right thing' with having a `visit_schema` (introduced in the other PR) and a `logical_schema()` function  (added here) in order to facilitate visiting the snapshot schema. Additionally I've moved the schema-related things up from `scan` module to top-level in ffi crate. Exact changes listed below; this PR updates tests/examples to leverage the new changes.
1. Remove `visit_snapshot_schema()` API
2. Add a new `logical_schema(snapshot)` API so you can get the schema of a snapshot and use the `visit_schema` directly
3. Renames `free_global_read_schema` to just `free_schema`
4. Moves `SharedSchema` and `free_schema` up from `mod scan` into top-level `ffi` crate. 
existing UT
> feat!(ffi): remove `visit_snapshot_schema`, add `logical_schema`

- .github/workflows/build.yml
- .github/workflows/default-kernel-features
- .github/workflows/semver-checks.yml
- README.md
- integration-tests/test-all-arrow-versions.sh
- kernel/Cargo.toml
- kernel/src/arrow.rs
- kernel/src/parquet.rs
If both arrow_53 and arrow_54 are specified, just use arrow_53
Also update the README for the new situation.
I'd like to emit a warning if more than one feature is enabled, but there is no `compiler_warning!`. See [here](https://internals.rust-lang.org/t/pre-rfc-add-compile-warning-macro/9370) for some discussion. If reviewers feel the `must_use` hack would be worth it, I can add it.
> Support --all-features again

- kernel/src/arrow.rs
- kernel/src/parquet.rs
- test-utils/Cargo.toml
If we try and have a `need_arrow` flag we can make that include the code line: `pub use arrow_53::*` but we _cannot_ have it actually pull in the dependency. Pulling in the dependency is purely expressed in `Cargo.toml`, so the `use` just fails because we don't _have_ an arrow_53 dependency in that case.
We can do some gross stuff in `build.rs` to inject the dependency, but even that doesn't apply to crates that depend on us so it only works if just compiling `delta-kernel` but isn't actually helpful for the use case we want.
So I kept the `need-arrow` dep as a way for us to express that something needs arrow enabled, but rather than trying to do the import, it just issues a `compile_error` asking you to pick an arrow version.
Perhaps we can get something more clever in the future, but …
> fix: Make having `need_arrow` + no arrow a compiler error

- CHANGELOG.md
- Cargo.toml
- README.md
- ffi/Cargo.toml
- kernel/Cargo.toml
> Release 0.7.0

- Cargo.toml
- kernel/Cargo.toml
Current chrono 0.4.40 breaks building arrow, pin chrono to a prior version that does not break arrow.
CI/CD
> pin chrono version to fix arrow compilation failure

- ffi/examples/visit-expression/expression.h
- ffi/examples/visit-expression/expression_print.h
- ffi/src/expressions/kernel.rs
The FFI expression visitor code incorrectly passes a `(u64, u64)` pair to `visit_literal_decimal` callback, representing the upper and lower half of an `i128` decimal value. It should actually be `(i64, u64)` to preserve signedness.
The expression visitor callback `visit_literal_decimal` now takes `i64` for the upper half of a 128-bit int value.
Updated the example code.
> fix!(ffi): Visit decimals as signed values

- ffi/examples/read-table/read_table.c
- ffi/src/lib.rs
- ffi/src/scan.rs
- test-utils/src/lib.rs
Make `get_partition_column_count` and `get_partition_columns` take a snapshot so engines can work this out at planning time without creating a scan.
The previous methods to get this info out of a scan have been removed.
The old functions that took snapshots have been removed
New unit test
> feat!(ffi): Make get_partition_column* work on a snapshot.

- Cargo.toml
`Url` crate now has MSRV with default unicode backend of rustc `1.81`. instead of fighting this, we will just bump up our MSRV from `1.80` to `1.81` seeing as (1) a large part of the ecosystem (datafusion, polars (though still states `1.80` in README), delta-rs, etc.) already is on `1.81` and (2) `Url` is a rather foundational crate so if they bump it seems reasonable to assume that many consumers will too
bumping MSRV from `1.80` to `1.81`
MSRV test
> fix!: bump MSRV to 1.81

- CHANGELOG.md
- Cargo.toml
- README.md
- ffi/Cargo.toml
- kernel/Cargo.toml
> release 0.8.0

- Cargo.toml
Updates HDFS dependencies to newest versions according to [compatibility matrix](https://github.com/datafusion-contrib/hdfs-native-object-store?tab=readme-ov-file#compatibility).
I expect current CI pipeline to cover this since there is a [HDFS integration test](https://github.com/delta-io/delta-kernel-rs/commit/1f57962207ae6256e7189a9ec5aa13be33d734f9). Also, I have run tests successfully (apart from code coverage due to missing CI secret) on [my fork](https://github.com/rzepinskip/delta-kernel-rs/commit/d87922de6556fc77ea584dbc9b11ad64ba243278).
> Update HDFS dependencies

- kernel/src/actions/mod.rs
- kernel/src/table_configuration.rs
- kernel/src/table_features/mod.rs
This PR adds two functions to TableConfiguration: 
1) check whether appendOnly table feature is supported
2) check whether appendOnly table feature is enabled
It also enabled writes on tables with `AppendOnly` writer feature.
I check that write is supported on Protocol with `WriterFeatures::AppendOnly`.
> feat: Add check for whether appendOnly table feature is supported or enabled 

- ffi/src/lib.rs
- kernel/src/scan/mod.rs
- kernel/src/snapshot.rs
- kernel/src/table_changes/scan.rs
- kernel/src/table_configuration.rs
- kernel/src/transaction.rs
Refactor snapshot.schema() to return a SchemaRef
resolves https://github.com/delta-io/delta-kernel-rs/issues/710
Breaking: changes `snapshot.schema()` API to return a `SchemaRef` (`Arc<Schema>`) instead of an `&Schema`
existing
> refactor!: make `snapshot.schema()` return a `SchemaRef`

- kernel/examples/inspect-table/src/main.rs
- kernel/src/actions/set_transaction.rs
- kernel/src/log_segment.rs
- kernel/src/scan/mod.rs
small change: `replay` generally refers to the work we do to resolve actions during log replay. I've renamed `LogSegment::replay` to `LogSegment::read_actions` since this method does just that: reads actions, but doesn't actually do tangible 'replay' work (Add/Remove matching, etc.).
just docs/rename. no material changes.
> refactor: rename `LogSegment::replay` to `LogSegment::read_actions`

- ffi/src/expressions/engine.rs
- ffi/src/expressions/kernel.rs
These were never intended to be public, so just fixing that.
- `visit_expression_internal`: is private
- `unwrap_kernel_expression`: is `pub(crate)`
Existing tests
> refactor!: make visit_expression_internal  private, and unwrap_kernel_expression pub(crate)

- .cargo/config.toml
- .gitignore
According to [arrow docs] we should ensure that we have `-C target-cpu=native` for rustc to generate best available instructions (SIMD, etc.) for our architecture
[arrow docs]: https://crates.io/crates/arrow
> misc: add .cargo/config.toml with native instruction codegen

- kernel/src/lib.rs
- kernel/src/log_replay.rs
- kernel/src/scan/log_replay.rs
**No behavioral changes were introduced, this is purely a refactoring effort**
This PR extracts the core deduplication logic from the `AddRemoveDedupVisitor` in order to be shared with the incoming `CheckpointVisitor`. For a bigger picture view on how this refactor is helpful, please take a look at the following PR which implements the `CheckpointVisitor` with an embedded `FileActionsDeduplicator` that will rebase this PR once merged. [[link to PR]](https://github.com/delta-io/delta-kernel-rs/pull/738).
This `FileActionsDeduplicator` lives in the new top-level `log_replay` mod as it will be leveraged in the nested `scan/log_replay` mod and the incoming `checkpoints/log_replay` mod. There are also additional traits & structs that the two `log_replay` implementations will share via this new …
> refactor: extract deduplication logic from `AddRemoveDedupVisitor` into embeddable `FileActionsDeduplicator`

- acceptance/tests/other.rs
- kernel/src/actions/schemas.rs
- kernel/src/log_segment.rs
- kernel/src/log_segment/tests.rs
- kernel/src/snapshot.rs
This PR renames `CheckpointMetadata` to `LastCheckpointHint` in order not to clash with the incoming `CheckpointMetadata` [[link to PR]](https://github.com/delta-io/delta-kernel-rs/pull/781). 
Moved to another PR
~~This PR also changes the types of fields in the `LastCheckpointHint`. This was done to unblock the in-flight work for single-file checkpoint write support, which includes the creation of the `_last_checkpoint` file. As `usize` and `u64` primitives are not supported, and we want to avoid a mismatch of field types we read v.s. write, we are updating the types to `i64`.  There is an overarching github issue for converting field types to unsigned integers (u64, usize) where semantically appropriate (such as for `LastCheckpointHint.version`... ) and adding proper support for these …
> refactor: Rename `_last_checkpoint` from `CheckpointMetadata` to `LastCheckpointHint`

- ffi/src/scan.rs
- ffi/tests/invalid-handle-code/private-constructor.stderr
- kernel/src/engine/default/parquet.rs
- kernel/src/path.rs
- kernel/src/scan/data_skipping.rs
- kernel/src/scan/mod.rs
- kernel/src/scan/state.rs
builds currently broken due to rustc 1.86 changing an error message + new clippy lints. this PR updates expected output to the new error and does two clippy lints:
1. `next_back()` instead of `last()` on iterators
2. docstring indentation updates
> fix: update compilation error and clippy lints for rustc 1.86

- kernel/src/actions/mod.rs
- kernel/src/table_changes/log_replay/tests.rs
- kernel/src/table_changes/mod.rs
- kernel/src/table_configuration.rs
- kernel/src/table_features/column_mapping.rs
- kernel/src/table_features/mod.rs
Renamed ReaderFeatures and WriterFeatures to ReaderFeature and WriterFeature
`cargo test`
> refactor!: Rename enums of ReaderFeatures and WriterFeatures 

- ffi/examples/read-table/arrow.c
- ffi/src/engine_funcs.rs
- kernel/examples/read-table-multi-threaded/src/main.rs
- kernel/src/actions/deletion_vector.rs
- kernel/src/engine/arrow_data.rs
- kernel/src/engine/arrow_expression/mod.rs
- kernel/src/engine/arrow_expression/tests.rs
- kernel/src/engine/default/filesystem.rs
- kernel/src/engine/default/mod.rs
- kernel/src/engine/mod.rs
- kernel/src/engine/sync/mod.rs
- kernel/src/lib.rs
- kernel/src/log_segment.rs
- kernel/src/log_segment/tests.rs
- kernel/src/scan/data_skipping.rs
- kernel/src/scan/log_replay.rs
- kernel/src/scan/mod.rs
- kernel/src/scan/state.rs
- kernel/src/snapshot.rs
- kernel/src/table_changes/log_replay.rs
- kernel/src/table_changes/log_replay/tests.rs
- kernel/src/table_changes/mod.rs
- kernel/src/table_changes/scan.rs
- kernel/src/table_changes/scan_file.rs
- kernel/src/transaction.rs
- kernel/src/utils.rs
- kernel/tests/read.rs
Rust doesn't encourage the `get_` prefix for getters because it's redundant and anyway a getter is allowed to have the same name as the field it exposes. Remove the prefix from the various engine interfaces. Additionally, rename `get_evaluator` as `new_expression_evaluator` to accurately reflect that it is _NOT_ a getter at all, but actually creates a new expression evaluator.
Finally, we also rename `ExpressionHandler` to `EvaluationHandler` because that trait is used to create expression _evaluators_, not expressions. Additionally, future work will differentiate generic "expressions" from "predicates" (boolean-valued expressions with special evaluation semantics), and that will likely necessitate defining a `EvaluationHandler::new_predicate_evaluator` method alongside the …
> refactor!: Remove get_ prefix from engine getters

- kernel/Cargo.toml
- kernel/src/path.rs
This PR introduces the helper methods:
- `new_uuid_parquet_checkpoint` which creates a new `ParsedCheckpointPath<Url>` for a uuid-named parquet checkpoint file at the specified version. The UUID-naming scheme looks like: `n.checkpoint.u.parquet`, where u is a UUID and n is the snapshot version that this checkpoint represents.
- `new_classic_parquet_checkpoint` which creates a new `ParsedCheckpointPath<Url>` for a classic-named parquet checkpoint file at the specified version. The classic-naming scheme looks like: `n.checkpoint.parquet`, where n is the snapshot version that this checkpoint represents.
- **Updates the `uuid` dependency to always include `v4` and `fast-rng` features:**
- This ensures that `uuid::new_v4()` is always available.
- The `fast-rng` feature improves performance …
> feat: add classic and uuid parquet checkpoint path generation

- acceptance/tests/other.rs
- kernel/src/actions/deletion_vector.rs
- kernel/src/engine/default/filesystem.rs
- kernel/src/engine/default/mod.rs
- kernel/src/engine/mod.rs
- kernel/src/engine/sync/mod.rs
- kernel/src/engine/sync/storage.rs
- kernel/src/lib.rs
- kernel/src/log_segment.rs
- kernel/src/log_segment/tests.rs
- kernel/src/scan/mod.rs
- kernel/src/scan/state.rs
- kernel/src/snapshot.rs
- kernel/src/table_changes/log_replay/tests.rs
- kernel/src/table_changes/mod.rs
- kernel/src/table_changes/scan_file.rs
- kernel/src/transaction.rs
Continuing the cleanup started by https://github.com/delta-io/delta-kernel-rs/pull/804, rename the class to eliminate the last vestiges of (ancient) "client" nomenclature.
The renamed class (and module) are public.
Rename-only operation, no functional changes. Compilation suffices.
> refactor!: Rename FileSystemClient to StorageHandler

- kernel/src/actions/deletion_vector.rs
- kernel/src/actions/mod.rs
- kernel/src/actions/visitors.rs
- kernel/src/engine/arrow_data.rs
- kernel/src/table_changes/mod.rs
- kernel/src/table_configuration.rs
- kernel/src/table_features/mod.rs
Instead of `Protocol` retaining a list of `Strings` representing lists of `ReaderFeature`/`WriterFeature`, we move to embed the fully parsed `ReaderFeature`s and `WriterFeature`s. This changes `Protocol.reader_features` and `Protocol.writer_features` fields from`Option<Vec<String>>` to Optional vecs of `ReaderFeatures` and `WriterFeatures` respectively. Critically, this includes a new `Unknown` variant which allows us to parse all possible strings in the protocol into `ReaderFeature`s and `WriterFeature`s but later detect if unknown features are present and fail when ensuring reader/writer features are supported. 
Breaking: new `ReaderFeature::Unknown(String)` and `WriterFeature::Unknown(String)` variants
(note that `Protocol` and fields are `pub(crate)`)
UT modification
> refactor!: adopt types for table features

- CHANGELOG.md
- Cargo.toml
- README.md
- ffi/Cargo.toml
- kernel/Cargo.toml
> release 0.9.0

- kernel/src/engine/parquet_row_group_skipping.rs
- kernel/src/engine/parquet_row_group_skipping/tests.rs
- kernel/src/kernel_predicates/mod.rs
- kernel/src/kernel_predicates/parquet_stats_skipping.rs
- kernel/src/kernel_predicates/parquet_stats_skipping/tests.rs
- kernel/src/kernel_predicates/tests.rs
- kernel/src/lib.rs
- kernel/src/scan/data_skipping.rs
- kernel/src/scan/data_skipping/tests.rs
- kernel/src/scan/log_replay.rs
- kernel/src/scan/mod.rs
The `predicates` module has a confusing name because it sits alongside the `expressions` module but does not actually define predicates (= boolean-valued expressions) at all. Instead, it contains kernel's implementation of predicate evaluation, used for e.g. data skipping and partition pruning.
Rename the module to `kernel_predicates` and rename corresponding classes like `PredicateEvaluator` to `KernelPredicateEvaluator`, to make their purpose more clear. This also helps clear the way for us to split out predicates as a separate concept from normal expressions, see https://github.com/delta-io/delta-kernel-rs/issues/765.
Module and class renames only. Compilation suffices.
> refactor: Rename predicates mod to kernel_predicates

- kernel/src/engine/default/filesystem.rs
- kernel/src/engine/default/mod.rs
- kernel/src/log_segment/tests.rs
- kernel/src/snapshot.rs
In the default engine implementation we currently employ a hack to determine if list results need additional sorting by inspecting the type name of the `ObjectStore` instance. The base heuristic is that local files will not be sorted so we check for `LocalObjectStore`.
However object stores might be wrapped in other stores to inject functionality or for testing purposes and different implementations for local files may suffer the same challenges.
This PR proposes to generalise the heuristic by sorting results whenever we encounter a `file` scheme within the list method.
`ObjectStoreStorageHandler::new` no longer takes `has_ordered_listing` as a parameter.
Current unit tests.
> fix: sort list results based on URL scheme

- ffi/src/test_ffi.rs
- kernel/src/engine/arrow_expression/tests.rs
- kernel/src/expressions/mod.rs
- kernel/src/kernel_predicates/mod.rs
- kernel/src/kernel_predicates/parquet_stats_skipping/tests.rs
- kernel/src/kernel_predicates/tests.rs
- kernel/src/scan/data_skipping/tests.rs
- kernel/tests/read.rs
Get rid of `impl Not for Expression` because it's hard to use directly (have to import `std::ops::Not`) and is also forced to take `self` instead of `impl Into<Expression>` as an argument (which we use way more often than `!`). Further, NOT is the only logical operator we could meaningfully overload in rust. AND/OR cannot be overloaded at all, and comparisons (via `PartialEq` and `PartialOrd`) have hard-wired return types that don't work for expressions.
Meanwhile `Expression::and` and `Expression::or` are hard to read as infix operators:
```rust
(a.lt(10).and(b.gt(20)).or(c.eq(42).and(d.le(100)))
```
so make them associated methods taking `impl Into<Expression>` instead of taking `self`:
```rust
Expr::or(
Expr::and(a.lt(10), b.gt(20)),
Expr::and(c.eq(42), d.le(100)),
)
```
Public …
> refactor!: Tidy up AND/OR/NOT API and usage

- ffi/src/expressions/kernel.rs
- kernel/src/engine/arrow_expression/evaluate_expression.rs
- kernel/src/expressions/mod.rs
- kernel/src/kernel_predicates/mod.rs
- kernel/src/kernel_predicates/parquet_stats_skipping.rs
- kernel/src/kernel_predicates/parquet_stats_skipping/tests.rs
- kernel/src/kernel_predicates/tests.rs
- kernel/src/scan/data_skipping.rs
- kernel/src/scan/data_skipping/tests.rs
Kernel only has two `VariadicExpression` variants: `AND` and `OR`. They are actually quite special because they hard-wire the assumption of short circuiting evaluation over boolean inputs. Those assumptions are incompatible with basically all future variadic expression types we might add, e.g. `XOR` does not short-circuit and `COALESCE` is not boolean-input. 
To avoid confusion, rename the "variant" operation to "junction" (AND = conjunction, OR = disjunction). 
NOTE: If we ever decide to support any true variadic expressions in the future (`XOR`, `COALESCE`, `SUM`, `MIN`, etc), it would mean (re-)introducing `VariadicOperation`, `VariadicExpression`, and `Expression::Variadic` alongside their `Junction`-related counterparts.
`VariadicOperation`, `VariadicExpression` , and …
> refactor!: Rename VariadicExpression to JunctionExpression

- ffi/src/expressions/engine.rs
- ffi/src/expressions/kernel.rs
- ffi/src/lib.rs
- ffi/src/scan.rs
- kernel/src/engine/arrow_data.rs
- kernel/src/engine/arrow_expression/evaluate_expression.rs
- kernel/src/engine/default/filesystem.rs
- kernel/src/expressions/mod.rs
- kernel/src/kernel_predicates/mod.rs
- kernel/src/log_segment/tests.rs
- kernel/src/scan/data_skipping.rs
- kernel/src/scan/mod.rs
- kernel/src/table_changes/scan_file.rs
This PR applies various cosmetic improvements that I noticed while working on other changes, but did not want to merge for hygiene reasons. Instead, I collected them together into a single hygiene-only PR.
Removing `KernelExpressionVisitorState::new` in favor of the already-existing `KernelExpressionVisitorState::default`.
Refactoring and comments. Compilation suffices.
> refactor: Grab bag of cosmetic tweaks and comment updates

- derive-macros/Cargo.toml
- derive-macros/src/lib.rs
- ffi/Cargo.toml
- ffi/src/handle.rs
- ffi/src/lib.rs
- kernel/Cargo.toml
- kernel/src/actions/mod.rs
- kernel/src/actions/visitors.rs
- kernel/src/lib.rs
- kernel/src/log_segment.rs
- kernel/src/path.rs
- kernel/src/schema/mod.rs
- kernel/src/snapshot.rs
- kernel/src/table_configuration.rs
In an effort to simplify our system of having an `internal_api` API this PR introduces an `#[internal_api]` attribute to annotate functions that are `pub(crate)` to make them `pub` when the `internal_api` feature flag is enabled. In this process, the PR removes our dependency on `visibility` crate (and hopefully makes it easier to introduce/track our 'internal' APIs). Note that there's also a small `internal_mod!` macro which is used to workaround the limitation of rustc disallowing attributes on non-inline modules.
~Stacked on #834~
build
> refactor: new `#[internal_api]` macro instead of `visibility` crate

- ffi/src/error.rs
ryan and I had a new learning (during exploration of `impl<T: EvaluationHandler + ?Sized> EvaluationHandlerExtension for T {}`) and just applying that approach to `impl<T: ExternEngine + ?Sized> AllocateError for &T {}` instead of  `impl AllocateError for &dyn ExternEngine {}`
> fix: tiny change for `impl AllocateError for T: ExternEngine`

- kernel/src/actions/mod.rs
- kernel/src/actions/set_transaction.rs
- kernel/src/expressions/scalars.rs
- kernel/src/lib.rs
- kernel/src/transaction.rs
- kernel/tests/write.rs
(part of idempotent writes support) this PR adds `transaction.with_transaction_id(app_id: String, version: i64, last_updated: Option<i64>)` API for commiting `txn` actions to the log. The only invariant imposed by kernel (as indicated by the [spec](https://github.com/delta-io/delta/blob/master/PROTOCOL.md#transaction-identifiers)) is that each `app_id` in a commit is unique.
> The semantics of the application-specific version are left up to the external system. Delta only ensures that the latest version for a given appId is available in the table snapshot. The Delta transaction protocol does not, for example, assume monotonicity of the version and it would be valid for the version to decrease, possibly representing a "rollback" of an earlier transaction.
Note that in order to make this …
> feat: add `transaction.with_transaction_id()` API

- kernel/src/engine/default/json.rs
- kernel/src/engine/sync/json.rs
This PR adds support for overwriting JSON files in both the `DefaultEngine` and `SyncEngine`.
Previously, the `write_json_file` implementations ignored the `overwrite` flag, as there was no use case requiring it. However, with the ongoing work in #851, engines are now expected to support overwriting in their `write_json_file` implementations- since the `_last_checkpoint` file will likely already exist at write time.
Both the `DefaultEngine` and the `SyncEngine` have the following new unit-test coverage:
- `test_write_json_file_without_overwrite`
- `test_write_json_file_overwrite`
> feat: overwrite logic in `write_json_file` for default & sync engine 

- NOTICE
- kernel/Cargo.toml
- kernel/examples/inspect-table/Cargo.toml
- kernel/examples/read-table-changes/Cargo.toml
noticed we had a few unused dependencies - ran across a handy tool [`cargo-udeps`](https://github.com/est31/cargo-udeps) to help out
> chore: remove unused dependencies

- README.md
The `rust-analyzer.cargo.features` setting only controls feature flags. Since acceptance is its now it's own crate, we should drop it from that list, otherwise rust-analyzer will try to pass `--features acceptance` at the workspace root (which Cargo will reject).
> docs: remove `acceptance` from `rust-analyzer.cargo.features` in README

- kernel/src/actions/set_transaction.rs
- kernel/src/snapshot.rs
- kernel/tests/write.rs
In an effort to support idempotent writes: adds a new API on `Snapshot` to fetch the latest version (latest `txn` action version) for a specific application id.
Future work: expose an api for fetching _all_ `txn` actions.
New `Snapshot:: get_app_id_version(self: Arc<Self>, app_id: &str, engine: &dyn Engine)` API for fetching the latest application id of a `txn` action.
added to `write.rs`
resolves #846
> feat: add `snapshot.get_app_id_version(app_id, engine)`

- kernel/src/engine/arrow_expression/tests.rs
- kernel/src/expressions/literal_expression_transform.rs
- kernel/src/expressions/scalars.rs
- kernel/src/kernel_predicates/tests.rs
- kernel/src/scan/log_replay.rs
- kernel/src/scan/mod.rs
- kernel/src/table_changes/physical_to_logical.rs
- kernel/tests/read.rs
Improve readability of some test code by using `Expr` instead of `Expression`. Most tests already did this.
Symbol name change, compilation suffices.
> chore: Test code uses Expr shorthand for Expression

- ffi/src/expressions/kernel.rs
- ffi/src/schema.rs
- ffi/src/test_ffi.rs
- ffi/tests/test-expression-visitor/expected.txt
- kernel/src/engine/arrow_conversion.rs
- kernel/src/engine/arrow_expression/mod.rs
- kernel/src/engine/parquet_row_group_skipping.rs
- kernel/src/engine/parquet_row_group_skipping/tests.rs
- kernel/src/expressions/mod.rs
- kernel/src/expressions/scalars.rs
- kernel/src/kernel_predicates/tests.rs
- kernel/src/schema/mod.rs
128-bit decimal precision is constrained to `1..=38` and scale is constrained to `0..=precision`. So far, the code only enforced that constraint for `PrimitiveType::Decimal` on an opt-in basis, with little or no enforcement on `Scalar::Decimal` values. In particular, there was not code in place at all to enforce that the decimal's i128 value actually fit within the specified precision.
Fix both problems by introducing new `DecimalType` and `DecimalValue` structs, which respectively replace unnamed tuple args as the payload of `PrimitiveType::Decimal` and `Scalar::Decimal`. This, in turn, allows us to make the struct members private, forcing all instances through a constructor that can validate its inputs.
Fixes https://github.com/delta-io/delta-kernel-rs/issues/853
The signatures of …
> fix!: Enforce precision/scale correctness of Decimal types and values

- kernel/src/scan/mod.rs
- kernel/src/table_changes/scan.rs
TLDR: Disable predicate pushdown in `Scan::execute` API (and CDF API too) since it currently breaks DV application.
The `Scan::execute` function currently combines the `Scan::scan_metadata()` (and the needed visiting, etc.) to get the `ScanFiles`, then for each scan file, performs the corresponding DV and parquet read before applying transforms/schemas and eventually handing back 'final data' to the user (in the form of a `ScanResult` which is just filtered engine data).
The problem lies in the application of the DV to the data in the presence of predicates. currently everything is positional, that is, if we read a DV that indicates rows 1, 5, and 10 are deleted from a record batch, then `Scan::execute` will simply apply those positional deletions after reading the parquet file. This may …
> fix: disable predicate pushdown in `Scan::execute`

- ffi/src/expressions/engine.rs
- kernel/src/engine/arrow_expression/tests.rs
- kernel/src/expressions/mod.rs
- kernel/src/expressions/scalars.rs
- kernel/src/kernel_predicates/parquet_stats_skipping/tests.rs
- kernel/src/scan/data_skipping.rs
- kernel/src/scan/mod.rs
- kernel/src/table_changes/physical_to_logical.rs
- kernel/src/table_changes/scan_file.rs
- kernel/tests/read.rs
The existing `impl<T: Into<Scalar>> From<T> for Expression` was too liberal and implicit, making code harder to read and making it harder to determine where ordinary values like `10` or `"hi"` were treated as expression literals. Replace that with `impl From<Scalar> for Expression` instead, and update call sites to use `Expression::literal` as needed.
Removed a trait impl for pub type `Expression`. 
Existing unit tests
> refactor!: Make literal expressions more strict

- kernel/src/engine/arrow_expression/mod.rs
- kernel/src/engine/default/mod.rs
See title.
Compilation suffices.
> chore: Arrow DefaultExpressionEvaluator need not box its inner expression

- kernel/src/expressions/mod.rs
`ExpressionTransform::recurse_into_junction` was weirdly calling the seemingly unrelated `ExpressionTransform::recurse_into_struct`, because it happened to accomplish the desired result. Pull out the common code to a proper helper function that both call sites can use. Also make it templated, so that it keeps working when we eventually split out predicates as a different type from normal expressions.
Code movement only. Existing unit tests cover it.
> refactor: Expression transforms use new recurse_into_children helper

- kernel/src/engine/arrow_expression/tests.rs
- kernel/src/expressions/mod.rs
The `lt_eq` and `gt_eq` methods of `Expression` are nearly-unused, with just a few call sites in test code. Remove them in favor of the more rustic [`le`](https://doc.rust-lang.org/std/cmp/trait.PartialOrd.html#method.le) and [`ge`](https://doc.rust-lang.org/std/cmp/trait.PartialOrd.html#method.ge) methods that they alias.
Removed public methods from `impl Expression`
Compilation suffices.
> refactor!: Remove nearly-unused expression lt_eq/gt_eq overloads

- kernel/src/expressions/mod.rs
- kernel/src/expressions/transforms.rs
- kernel/src/scan/mod.rs
See title. Too much code was accumulating in the main expressions module.
`ExpressionTransform` and `ExpressionDepthChecker` moved to a sub-module.
Pure code movement, no functional changes.
> refactor!: Move expression transform code to its own module

- kernel/Cargo.toml
- kernel/src/engine/default/storage.rs
This provides the ability for downstream crates to insert their own URL handlers, and offers a path for delta-kernel-rs to reduce its dependency on hdfs-native-object-store for all consumers of the crate.
I hacked this out modeling off something similar that I did in delta-rs to allow pluggable storage handlers, which is hugely beneficial to reducing the dependency scope of its core module. In discussing arrow-55 upgrade challenges with Zach I proposed this as a way to help simplify the upgrade path around arrow-55 and object-store-0.12. Side benefit of a slightly smaller dependency footprint for downstream consumers :)
> feat!: introduce the ability for consumers to add ObjectStore url handlers

- kernel/src/expressions/mod.rs
- kernel/src/kernel_predicates/mod.rs
- kernel/src/kernel_predicates/parquet_stats_skipping.rs
- kernel/src/scan/data_skipping.rs
The expressions module is pretty big, shuffling some code around to organize it better.
Reordered variants of the `BinaryExpressionOp` enum. Code that casts the variants `as isize` could notice.
Pure code movement, compilation suffices.
> refactor!: Code movement in expression-related code

- README.md
- kernel/Cargo.toml
- kernel/src/arrow_compat.rs
- kernel/src/engine/default/storage.rs
1. README fixes to clarify new arrow semantics
2. default to arrow-55 in all cases except when user passes ONLY `arrow-54`
3. `insert_url_handler` returns `delta_kernel::Error` instead of `object_store::Error` and we return err instead of panic.
`insert_url_handler` returns `delta_kernel::Error` instead of `object_store::Error`
existing. `cargo tree` to check deps and manually verified that our code blows up if we remove `arrow-54` from `arrow_compat` and specify `arrow-54` flag (better testing coming later).
> fix!: arrow and panic fixes

- kernel/src/engine/default/filesystem.rs
- kernel/src/engine/sync/storage.rs
- test-utils/src/lib.rs
remove `abs_diff` - it's in rust 1.81
existing
> chore: remove abs_diff since we have rust 1.81

- kernel/src/table_configuration.rs
- kernel/src/table_features/mod.rs
This PR adds checks to TableConfiguration for in-commit timestamps. The following are introduced: 
- `in_commit_timestamps_supported`: true if ICT is supported
- `in_commit_timestamps_enabled`: true if ICT is enabled
- `in_commit_timestamp_enablement`: Gets enablement version and timestamp
This adds a WriterFeature, making it a breaking change.
Check the following cases:
- Supported but not enabled
- Supported and enabled, but is missing the enablement timestamp
- Fully supported and Enabled.
> feat!: Add in-commit timestamp table feature

- acceptance/tests/other.rs
- kernel/src/engine/default/json.rs
- kernel/src/engine/default/parquet.rs
- kernel/tests/write.rs
Several parts of the code (fortunately mostly in tests) incorrectly use `object_store::Path::from(url.path())`. `Url::path` returns a URI-encoded string, and `Path::from` applies URI encoding as well, resulting in double-encoded strings. 
Fortunately, `object_store::Path::from_url_path` exists for just this scenario. Use it.
Related to https://github.com/delta-io/delta-kernel-rs/issues/918
Existing unit tests continue to pass. A larger change would be needed to categorically rule out this kind of issue.
> fix: Use object_store::Path::from_url_path when appropriate

- kernel/src/expressions/literal_expression_transform.rs
~stacked on #881~
Adds support for maps and arrays (just treated as leaves) in literal_expression_transform.
new UT
> feat: support maps and arrays in literal_expression_transform

- kernel/src/actions/mod.rs
- kernel/src/lib.rs
Turns out `rustfmt` won't format module files that are included via a macro. See [here](https://github.com/rust-lang/rustfmt/issues/3253). 
This meant things like `log_segment.rs` that were included via `internal_mod!` were not getting formatted.
This removes that macro and just uses the "double include" gated by feature flags, which `rustfmt` can handle.
Making sure that miss-formatted code in the effected modules is now formatted when running `cargo fmt`.
> fix: Don't include modules via a macro

- kernel/src/engine/parquet_row_group_skipping/tests.rs
- kernel/src/kernel_predicates/mod.rs
- kernel/src/kernel_predicates/parquet_stats_skipping.rs
- kernel/src/scan/data_skipping.rs
Upcoming support for opaque engine expressions (see https://github.com/delta-io/delta-kernel-rs/issues/764) will require passing `&dyn DataSkippingPredicate` to opaque expression operations, so they can correctly evaluate their child expressions.
The trait was already almost dyn-compatible, except that `finish_eval_pred_junction` took an `impl IntoIterator` (now changed to `&dyn Iterator`). 
While we're at it, simplify the trait's type signature by combining associated types `TypedStat` and `IntStat` to just one `ColumnStat` type:
```rust
// Before
&dyn DataSkippingPredicateEvaluator<Output = Pred, TypedStat = Expr, IntStat = Expr>
&dyn DataSkippingPredicateEvaluator<Output = bool, TypedStat = Scalar, IntStat = i64>
// After
&dyn DataSkippingPredicateEvaluator<Output = Pred, ColumnStat = …
```
> refactor!: Make DataSkippingPredicate dyn compatible

- ffi/src/expressions/engine_visitor.rs
- ffi/src/expressions/kernel_visitor.rs
- ffi/src/expressions/mod.rs
- ffi/src/scan.rs
Reorganize the FFI code so its two visitor modules contain only visitor code, and their names reflect it.
Code movement in the FFI crate:
1. Rename `ffi::expressions::engine` mod as `kernel_visitor` to more accurately reflect the module's existing doc comment: "Defines [`KernelExpressionVisitorState`]".
2. Rename `ffi::expressions::kernel` mod as `engine_visitor` to more accurately reflect the module's existing doc comment: "Defines [`EngineExpressionVisitor`]".
3. Move the `free_kernel_[expression|predicate]` functions to the expressions mod, which already defines the corresponding shared handle types those functions work with. 
4. Move the `EnginePredicate` struct to the `ffi::scan` module, which is currently the type's only consumer.
Code movement. Compilation suffices.
> refactor!: Code movement in FFI crate

- ffi/src/engine_funcs.rs
- kernel/src/engine/default/filesystem.rs
- kernel/src/engine/default/json.rs
- kernel/src/engine/default/parquet.rs
- kernel/src/lib.rs
Between arrow-54 and arrow-55, some uses of `usize` changed to `u64` which causes compilation errors if not converted. Previously, we just added a `try_into` call, which always compiles thanks to a blanket `impl<T> TryInto<T> for T`, but generates a clippy warning on arrow-55 where it's redundant. 
Unfortunately, the annotations added to ignore those clippy warnings come with undesirable side effects:
1. There is no compiler help to encourage removing the redundant code, once it's no longer needed.
2. Some annotated sites always need the conversion, regardless of which arrow version is used
Replace the clippy annotations with a separate conditionally compiled `let` that only does the `try_into` when compiling against arrow-54, and fix the sites that were already incorrect. Once arrow-54 …
> chore: Conditional compilation instead of suppressing clippy warnings

- kernel/src/log_segment.rs
- kernel/src/log_segment/tests.rs
- kernel/src/path.rs
- kernel/src/snapshot.rs
- test-utils/src/lib.rs
This is a "pre-factor" pr. It makes our listing code aware of [compacted log files](https://github.com/delta-io/delta/blob/master/PROTOCOL.md#log-compaction-files), and stores them in the log segment. It handles filtering out compactions that are outside the range of what has been requested or that are not useful due to a checkpoint.
A follow-on PR will handle actually using these files in place of the underlying commits.
This PR introduces a new struct: `ListedLogFiles` which allows our listing to more easily return multiple types of files. This replaces the old tuple of `(commit_files, checkpoint_files)`, as extending that to `(commit_files, compaction_files, checkpoint_files)` felt unwieldy. There will be more types as we add crc support (and potentially others) as well. This …
> feat: Store compacted log files in LogSegment

- kernel/src/checkpoint/mod.rs
Writing data is mostly an async operation in Rust. Since the `CheckpointDataIterator` needs to be handed back to kernel on `finalize`, we need to be able to use it across `awaits`. As such we require the internal boxed iterator to also be `Send`.
This came up when integrating checkpoint writing in `delta-rs`. With the proposed change, it works.
> fix: allow CheckpointDataIterator to be used across await

- kernel/src/expressions/scalars.rs
- kernel/src/table_changes/physical_to_logical.rs
- kernel/tests/cdf.rs
This PR changes the record batches produced by `TableChangesScan::execute` to return `timestamp` column instead of `timestamp_ntz`. Previously, the TableChanges schema stated that the batches would have timestamp type, but the record batches returned did not match that.
The reference implementation of change data feed returns timestamp columns, so that is what we will use.
The physical to logical translation test is updated to ensure `Timestamp` type is returned.r
The cdf integration test ensures that the returned arrow batches match the table's schema.
> fix!: Fix timestamp ntz in physical to logical cdf

- .cargo/config.toml
`target-cpu=native` rustflags instructs rustc to optimize code specifically for the CPU architecture of the machine that's compiling the code. this is a problem for cross compilation (see #959)
instead, we can just have local `~/.cargo/config.toml` with our own specific RUSTFLAGS.
compile: `cargo build --package delta_kernel_ffi --workspace --target x86_64-apple-darwin` from an aarch64 mac
resolves #959
> fix: remove `target-cpu=native` rustflags

- derive-macros/src/lib.rs
- kernel/src/actions/mod.rs
- kernel/src/engine_data.rs
Rename `drop_null_container_values` to `allow_null_container_values`.
`#[drop_null_container_values]` is a bad name for the annotation.  It really means `#[allow_null_container_values]`, since it just sets the `nullable` flag on the `StructField`. The actual dropping is a contract of GetData (specifically `materialize`).
If we had an action that wanted to keep nulls, they could (misleadingly) put `#[drop_null_container_values]` and then not use `materialize`, and just build their own `HashMap<String, Option<String>>` using `MapItem::get`.
This PR also updates a few comments to make the above more clear when reading the code.
Not really public API, but the attribute is public in a sense.
Existing unit tests
> fix: Rename `drop_null_container_values` to `allow_null_container_values`

- kernel/src/engine/arrow_expression/evaluate_expression.rs
- kernel/src/engine/arrow_expression/mod.rs
- kernel/src/engine/arrow_expression/tests.rs
Make arrow predicate evaluation directly invertible, similar to how kernel predicate evaluation already does it. This is a necessary precursor to supporting opaque predicates, because we don't know the best way to handle inputs of an inverted opaque predicate (should we invert the output, like NOT? Or invert the inputs, like XOR? Or do something clever like AND, which is inverts inputs and OR the results?). By factoring out an `inverted` flag, we can delegate the implementation of `NOT(<opaque pred>)` to the opaque predicate.
Expanded existing unit tests to cover inversion
> refactor: Make arrow predicate eval directly invertible

- kernel/examples/inspect-table/src/main.rs
- kernel/src/actions/domain_metadata.rs
- kernel/src/actions/set_transaction.rs
- kernel/src/checkpoint/log_replay.rs
- kernel/src/log_replay.rs
- kernel/src/log_segment.rs
- kernel/src/log_segment/tests.rs
- kernel/src/scan/log_replay.rs
- kernel/src/scan/mod.rs
We have many places which pass around the following tuple which contains a batch of EngineData of actions and a boolean to indicate whether or not it came from a commit file or a checkpoint or something else: `(Box<dyn EngineData>, bool)`. Inspired by #910 this encapsulates "actions batches" into a struct.
In order to easy the interpretation of these tuples this PR replaces the tuple with a simple pub(crate)-fields struct named `ActionsBatch`:
```rust
struct ActionsBatch {
actions: Box<dyn EngineData>,
is_log_batch: bool,
}
```
refactor. existing tests suffice
> refactor: Add `ActionsBatch`

- kernel/src/engine/arrow_expression/tests.rs
See title. The existing test code was unnecessarily hard to read.
Test-only change
> chore: Use consistent naming of kernel data type in arrow eval tests

- ffi/src/expressions/kernel_visitor.rs
- ffi/src/ffi_tracing.rs
- ffi/src/test_ffi.rs
- kernel/src/checkpoint/mod.rs
- kernel/src/engine/arrow_expression/evaluate_expression.rs
- kernel/src/engine/arrow_expression/mod.rs
- kernel/src/expressions/mod.rs
- kernel/src/kernel_predicates/mod.rs
- kernel/src/kernel_predicates/parquet_stats_skipping.rs
- kernel/src/lib.rs
- kernel/src/scan/data_skipping.rs
Pathfinding on https://github.com/delta-io/delta-kernel-rs/pull/686 exposed the fact that an engine implementing custom (opaque) expressions needs access to several kernel API that are currently private. Make them public and fix their doc comments. 
Also fix some broken doc comments for already-pub code, exposed by the following command (CI test gap?)
```
cargo doc --workspace --all-features
```
While we're at it, rename `Expression::predicate` to `Expression::from_pred` to be consistent with `Predicate::from_expr` (the old name was confusing to read at call sites).
`KernelPredicateEvaluator` and `KernelPredicateEvaluatorDefaults` are now pub.
Make `DataSkippingPredicateEvaluator` pub; add new type aliases `DirectDataSkippingPredicateEvaluator` and `IndirectDataSkippingPredicateEvaluator` …
> chore!: Make several types/function pub and fix their doc comments

- .github/workflows/build.yml
title: modify our CI docs builds to be `cargo doc --workspace --all-features`
> ci: cargo doc workspace + all-features

- kernel/src/log_segment.rs
- kernel/src/log_segment/tests.rs
Fixes #954
Specifically, I've added assert statements to check that:
- `ascending_commit_files` are contiguously sorted, from lowest to highest version
- `ascending_compaction_files` are sorted
- all elements within `checkpoint_parts` is a checkpoint
- all elements within `checkpoint_parts` share the same `version` and `file_type`
- if an element within `checkpoint_parts` is `LogPathFileType::MultiPartCheckpoint`, check that the length of vector equals to the `num_parts`
I ran `cargo nextest run` and passed all tests
> feat: Add `debug_assert` to the constructor of `struct ListedLogFiles`

- kernel/src/actions/visitors.rs
This PR adds a visitor for In-commit timestamps (ICT). This visitor only checks the first row in the batch because the spec states that CommitInfo must be the first action if ICT is enabled.
- Verify that the ICT is extracted only if CommitInfo is the first row.
- Verify that ICT is extracted when CommitInfo is the first row and In-commit timestamp is present.
> feat: Create visitor for getting In-commit Timestamp

- kernel/src/history_manager/mod.rs
- kernel/src/history_manager/search.rs
- kernel/src/lib.rs
This PR introduces the `binary_search_by_key_with_bounds` utility function and the `history_manager` module.
`binary_search_by_key_with_bounds` can be used to search over slices to find the least upper or greatest lower bounds. It uses a fallible key function to get comparable values from the slice. This is useful for performing binary search over fallible operations such as reading the in-commit timestamp from a commit file.
The search bounds are defined by `Bound::LeastUpper` and `Bound::GreatestLower`.
The following cases are checked:
- An exact match is present
- There are duplicate matches. Ensure that the search bounds are respected.
- Edge cases for GreatestLower and LeastUpper
- Cases where the search is out of range
- Error propagation from the key_fn to the caller.
> feat: Binary searching utility function for timestamp to version conversion

- kernel/src/table_configuration.rs
- kernel/src/table_features/mod.rs
- kernel/src/table_features/timestamp_ntz.rs
- kernel/tests/write.rs
Resolves #987.
And adds protocol validation: if the provided table has "TIMESTAMP_NTZ" column, it should have "timestampNtz" reader/writer features.
Support `TIMESTAMP_NTZ` column type for writes.
* Added test to `kernel/tests/write.rs`
* Added test to new `kernel/src/table_features/timestamp_ntz.rs`
> feat: enable "TimestampWithoutTimezone" table feature and add protocol validation for it

- kernel/src/scan/data_skipping.rs
- kernel/src/scan/data_skipping/tests.rs
delta-kernel-rs assumes stats to be accurate as microseconds (like the timestamp type they are represented), but delta spec states that `add.stats` min/max values truncate strings/timestamps to milliseconds:
> String columns are cut off at a fixed prefix length. Timestamp columns are truncated down to milliseconds
While that's okay for min-stats, it's incorrect for max-stats: the file's _actual_ max-value is anywhere from 0-999µs larger than the recorded stats max-value.
In the short-term we disable timestamp-based file skipping, and long term will explore a solution like adding 999us to our max stat (in follow-up issue).
New UT
follow-up in #1002
> fix: disable timestamp column for data skipping

- kernel/src/engine/default/parquet.rs
resolves #968 (I hope)
TLDR: Fixes kernel (default-engine) error when trying to read on azure.
`arrow-55` introduced [support for reading parquet metadata via suffix range requests](https://github.com/apache/arrow-rs/pull/7334) but since azure [doesn't support suffix range requests](https://github.com/apache/arrow-rs-object-store/blob/9c43521d3c8e86fdfc4df788a5a63e45e23093b7/src/azure/client.rs#L912-L918) whenever anyone tried reading an azure table with default-engine based on arrow-55 it [blew up](https://github.com/delta-io/delta-kernel-rs/issues/968).
This PR mitigates by re-adding the original `head` request so that we can pass the `file_size` to the `ParquetObjectReader::with_file_size` which states that when this API is used, the reader will ensure only bounded range requests are …
> fix: remove azure suffix range request

- kernel/examples/read-table-multi-threaded/src/main.rs
Previously in #957 we moved the code to use [`thread::scope`](https://doc.rust-lang.org/std/thread/fn.scope.html). This allows not  having to clone an engine arc, but also means that all the threads are implicitly joined at the end of the `scope` call.
This meant that we waited for the threads to exit before ever sending them any work, so the version on main hangs 😱 . 
Instead we need to move all the rest of the logic inside the scope call and only let the implicit joining happen at the end.
Running the program on a few tables
> fix: Move logic into the thread::scope call so it doesn't hang

- kernel/src/checkpoint/mod.rs
- kernel/src/checkpoint/tests.rs
previously, kernel always wrote `parts: 1` in the `_last_checkpoint` file since the kernel only supports single-file checkpoints and v2 checkpoints, NOT muti-part checkpoints (which are considered unsafe and will never be written by kernel). This was incorrect. The [protocol states](https://github.com/delta-io/delta/blob/master/PROTOCOL.md#last-checkpoint-file-schema) that the 'parts' field in `_last_checkpoint` is:
> The number of fragments if the last checkpoint was written in multiple parts. This field is optional.
Thus, we actually _must_ write `None` for single-part/v2 checkpoints in order to comply with the protocol. `Some(x)` implies a multi-part checkpoint with `x` parts.
modified UT
resolves #1043
> fix: always write `_last_checkpoint` with parts = None

- kernel/examples/common/Cargo.toml
- kernel/examples/common/src/lib.rs
- kernel/examples/inspect-table/Cargo.toml
- kernel/examples/inspect-table/src/main.rs
- kernel/examples/read-table-changes/Cargo.toml
- kernel/examples/read-table-changes/src/main.rs
- kernel/examples/read-table-multi-threaded/Cargo.toml
- kernel/examples/read-table-multi-threaded/src/main.rs
- kernel/examples/read-table-single-threaded/Cargo.toml
- kernel/examples/read-table-single-threaded/src/main.rs
Our examples have a lot of common code to get an engine, snapshot, table, etc. We want to add support for more options (like reading from different cloud providers), and we shouldn't have to add that code in multiple places.
This introduces a new `common` crate with all the shared options, and then each example can just `flatten` the set of args they need into their `Cli` struct.
Note that all the code in `common/src/lib.rs` is just copied from the existing examples.
Running all the examples
> feat: Introduce a crate for args that are common between examples

- kernel/src/engine/arrow_utils.rs
Previously we didn't reorder things that were inside a map. We actually already did compute the required reordering, but then just threw it away.
This uses that computed reordering and returns it in the mask/reorder phase, and then uses it in `reorder_struct_array` to properly recurse into maps and reorder elements.
We model a map reorder as a `ReorderIndex::Nested` variant. The index of the top level nested item says where the map itself should end up in the output. Then there are two nested `ReorderIndex`s, which specify how any inner things should be reordered. The code does  handle the case that a struct might be in a map but not need to be reordered. It checks if the computed nested reorder for keys or values doesn't actually require any work and will replace it with an `Identity` …
> feat: Support reordering structs that are inside maps in default parquet reader

- kernel/src/engine/arrow_expression/evaluate_expression.rs
- kernel/src/engine/arrow_expression/mod.rs
- kernel/src/engine/arrow_expression/opaque.rs
- kernel/src/engine/arrow_expression/tests.rs
Follow-up to 
* https://github.com/delta-io/delta-kernel-rs/pull/686
Add support for arrow evaluation of opaque expressions in the default engine. The new API allows engines to define their own expressions that operate on arrow record batches and which seamlessly fit into the arrow evaluation framework alongside normal kernel expressions.
Once this support lands, we can remove the existing `BinaryPredicateOp::In` predicate from the core kernel, and make it part of the default engine instead.
Add a new API for evaluating opaque expressions and predicates in the default engine.
New unit tests.
> feat: Add default engine support for arrow eval of opaque expressions

- kernel/src/actions/mod.rs
Engines (or integrators using `internal-api` may want to inspect some of the more descriptive fields on metadata, specifically `id`, `name`, `description`, `created_time`. This PR exposes these fields via accessors.
new accessors on `Metadata`
existing UT.
> feat: expose descriptive fields on metadata

- kernel/src/engine/default/json.rs
`PutMultipartOpts` deprecated in latest object_store (0.12.3)
`PutMultipartOpts` -> `PutMultipartOptions`
existing
> fix: rename object_store PutMultipartOpts

- kernel/src/log_segment.rs
- kernel/src/log_segment/tests.rs
This is a stacked PR. Please look at the _LAST_ commit of each PR for the files changed.
* [LogSegment constructor for timestamp conversion](https://github.com/delta-io/delta-kernel-rs/pull/895)
* [Commit to timestamp helper function](https://github.com/delta-io/delta-kernel-rs/pull/898)
* [ICT search bounds checking](https://github.com/delta-io/delta-kernel-rs/pull/899)
* [High level timestamp conversion APIs](https://github.com/delta-io/delta-kernel-rs/pull/900)
This PR adds a LogSegment constructor that will be used in timestamp to version conversion. The function `LogSegment::for_timestamp_conversion` creates a LogSegment made entirely of commits up to an optional end version.  
`LogSegment::for_timestamp_conversion` goes back to the earliest possible commit while maintaining …
> feat: Add log segment constructor for timestamp to version conversion

- kernel/src/actions/deletion_vector.rs
- kernel/src/actions/mod.rs
- kernel/src/engine/arrow_conversion.rs
- kernel/src/engine/default/executor.rs
- kernel/src/engine/default/file_stream.rs
- kernel/src/engine/default/filesystem.rs
- kernel/src/engine/default/parquet.rs
- kernel/src/lib.rs
- kernel/src/path.rs
- kernel/src/scan/mod.rs
- kernel/src/schema/mod.rs
changes TLDR:
1. add clippy lints to deny panic in non-test code
2. fix most of them
3. make follow ups for (1) kernel/src/engine/default/executor.rs #1112, (2) do the same lints + fixes in FFI crate #1114 
details:
after running across many PR reviews which rely on humans to catch panics, this PR attempts to automate much of this by introducing the following clippy lints to warn (=deny for us) on panics in prod code. note that we still allow it in test code.
```
clippy::unwrap_used,
clippy::expect_used,
clippy::panic
```
ran clippy
> refactor: deny panics in prod code

- kernel/Cargo.toml
in #1071 we made a rename based on a change that landed in `object_store` 0.12.3 - need to make sure cargo doesn't select an object_store before 0.12.3, else we get the following error since the rename only occurred in 0.12.3+
```
error[E0432]: unresolved import `crate::object_store::PutMultipartOptions`
--> kernel/src/engine/default/json.rs:264:9
|
264 |     use crate::object_store::PutMultipartOptions;
|         ^^^^^^^^^^^^^^^^^^^^^-------------------
|         |                    |
|         |                    help: a similar name exists in the module: `PutMultipartOpts`
|         no `PutMultipartOptions` in the root
```
manually
> fix: use object_store >= 0.12.3 for arrow 55 feature

- ffi/Cargo.toml
- ffi/src/engine_data.rs
- ffi/src/engine_funcs.rs
- ffi/src/lib.rs
- ffi/src/transaction/mod.rs
- ffi/src/transaction/write_context.rs
- kernel/tests/write.rs
- test-utils/src/lib.rs
This PR is a retake of https://github.com/delta-io/delta-kernel-rs/pull/550
This PR implements the ffi functions required to do appends. The main difference over https://github.com/delta-io/delta-kernel-rs/pull/550 is how it's tested: instead of using a C based example we now opt for a rust-based test that is able to re-used various testing-related utility functions that are used in the kernel tests. To do this cleanly, i've moved several functions over to the test-utils crate. 
- Adds new ffi functions related to appends / transactions
Using the `test_basic_append` in `ffi/src/transaction/mod.rs`. 
I would like to draw the reviewer's attention to:
- the concept of testing new ffi functionality through rust tests instead of a C example program
- usage of `tempfile::tempdir` to create a …
> feat: add append functions to ffi

- kernel/src/engine/ensure_data_types.rs
- kernel/src/utils.rs
This PR fixes a test that fails on an error message to work across all arrow versions.  the error message depends on the Debug print of arrow type. Due to this [commit](https://github.com/apache/arrow-rs/pull/7469), the debug print result differs between arrow versions. 
existing unit tests.
Indentation was tested by breaking a test and checking that the error message is easy to read.
> Fix failing test and improve indentation test error message

- kernel/src/log_segment.rs
- kernel/src/log_segment/tests.rs
fixes #995 
This PR moves the `require!()` check from `LogSegment::try_new()` —> `ListedLogFiles::try_new()`
Originally, this issue was meant to explore if we could add this check inside the `debug_asserts` of #986 . However, I don't think this is an invariant specified by the [Protocol.md](https://github.com/delta-io/delta/blob/master/PROTOCOL.md#delta-log-entries-1), so I think we should keep this as a runtime check.
+1 [Java kernel also has a runtime check](https://github.com/delta-io/delta/blob/5893f5c2bbccb9eea3b6d1b7c74bb72395269860/kernel/kernel-api/src/main/java/io/delta/kernel/internal/snapshot/LogSegment.java#L184)
Also, this was labeled as a "breaking change" because the name changes of an internal API. I've removed the tag.
I added test cases for testing the …
> refactor: Contiguous commit file checking inside `ListedLogFiles::try_new()`

- Cargo.toml
- uc-client/Cargo.toml
- uc-client/README.md
- uc-client/examples/uc-cli.rs
- uc-client/src/client.rs
- uc-client/src/config.rs
- uc-client/src/error.rs
- uc-client/src/lib.rs
- uc-client/src/models/commits.rs
- uc-client/src/models/credentials.rs
- uc-client/src/models/mod.rs
- uc-client/src/models/tables.rs
- uc-client/src/tests.rs
Add `uc-client` crate: experimental, minimal UC rust client. It implements the handful of APIs needed to interact with UC for catalog-managed tables. This create _will not be released_ in its current form and exists only to unblock future catalog-managed tables work.
Ran CLI example against existing UC deployment
> feat(catalog-managed): experimental uc client

- ffi/src/expressions/engine_visitor.rs
- kernel/examples/read-table-multi-threaded/src/main.rs
- kernel/src/actions/visitors.rs
- kernel/src/expressions/column_names.rs
- kernel/src/expressions/mod.rs
- kernel/src/expressions/transforms.rs
- kernel/src/scan/log_replay.rs
- kernel/src/scan/mod.rs
- kernel/src/table_changes/physical_to_logical.rs
- kernel/tests/read.rs
use `ExpressionRef` (`Arc<Expression>`) instead of owned `Expressions` in `Struct` and `Transform`
main changes:
- new `column_expr_ref!` macro
- Expression::Struct now takes a `Vec<ExpressionRef>` instead of `Vec<Expression>`
- expression transform changed accordingly
Expression::Struct now takes a `Vec<ExpressionRef>` instead of `Vec<Expression>`
correctness: existing UT
performance: manual (below) - seeing significant (~2x) speedups on wide/large scan_metadata
```
cargo b -r -p read-table-multi-threaded && \
time target/release/read-table-multi-threaded --metadata <table_path>
```
> perf!: ExpressionRef instead of owned for transforms

- kernel/src/schema/mod.rs
Closes: https://github.com/delta-io/delta-kernel-rs/issues/1121 
StructField.physical_name is made into an internal API. 
`StructField.physical_name` is now private (`internal-api`)
existing
> refactor!: Make `StructField.physical_name` internal

- kernel/src/log_segment.rs
- kernel/src/log_segment/tests.rs
- kernel/src/snapshot.rs
Push down reading `LastCheckpointHint` into (one of) `LogSegment` constructor. This is needed so that the LogSegment constructor can 'decide' if it needs to list - in the presence of a `log_tail` in CCv2 we may not need to list at all. Furthermore, even in the absence of CCv2, this should change is probably still useful in that the LogSegment::for_snapshot is called after the only place we read the `LastCheckpointHint` = reasonable to directly embed it. Note that to keep our existing unit tests i've refactored the `for_snapshot_impl` with the same signature as the old one.
For reviewers: i've split into two commits, first does material change, second updates callsites.
refactor: existing
> refactor(catalog-managed): push down _last_checkpoint read into LogSegment

- ffi/src/engine_funcs.rs
- kernel/examples/read-table-multi-threaded/src/main.rs
- kernel/src/actions/visitors.rs
- kernel/src/engine/arrow_expression/mod.rs
- kernel/src/lib.rs
- kernel/src/scan/data_skipping.rs
- kernel/src/scan/log_replay.rs
- kernel/src/scan/mod.rs
- kernel/src/scan/state.rs
- kernel/src/table_changes/log_replay.rs
- kernel/src/table_changes/scan.rs
- kernel/src/transaction/mod.rs
- kernel/tests/read.rs
Today, `EvaluationHandler::new_expression_evaluator` takes an owned `Expression` (`Predicate`) as input. 
This requires making expensive deep clones even when the caller already has an `ExpressionRef`.
(exactly the same analysis applies to `EvaluationHandler::new_predicate_evaluator`, `Predicate`, and `PredicateRef`)
Change the method signatures to take Arc instead. For single-use expressions, the additional heap allocation cost is minimal (measurable with only the tiniest expressions), and for frequently-used expressions it saves a lot of copying. 
NOTE: 
* The FFI `new_expression_evaluator` still takes an `&Expression`; we should consider whether it should take an `ExpressionRef` as well. 
* PRO: would allow expression reuse across the FFI boundary as well
* CON: requires introducing a …
> feat!: Expression evaluators take ExpressionRef as input

- kernel/src/listed_log_files.rs
prior PR made it private. this reverts back to being `internal-api`
visibility. compilation suffices.
> fix: make ListedLogFiles::try_new internal-api (again)

- kernel/src/checkpoint/log_replay.rs
Addressing https://github.com/delta-io/delta-kernel-rs/issues/1014, and implementing fix as suggested in issue.
This PR implements a short-circuit optimization for the checkpoint visitor code to improve performance when processing Delta Lake transaction logs during checkpoint creation.
Today, when a duplicate action is found, the system would still unnecessarily evaluate following action checks, even though the row was already determined to be excluded. 
To fix, we introduce a 4 states in the return with Option<DeltaResult<bool>>.
* Some(Ok(true)): Valid action found → include row, stop checking other types
* Some(Ok(false)): Action found but suppressed (duplicate/expired) → exclude row, stop checking other types
* None: No action of this type found → continue checking other action types …
> perf: make checkpoint visitor more efficient using short circuiting

- kernel/src/action_reconciliation/mod.rs
- kernel/src/checkpoint/mod.rs
- kernel/src/checkpoint/tests.rs
- kernel/src/lib.rs
- kernel/src/snapshot.rs
- kernel/src/utils.rs
This is a pure refactoring change to:
- Extract retention calculation logic into new module with a RetentionCalculator trait
- Update CheckpointWriter to use RetentionCalculator trait
The trait will be reused in the upcoming log compaction writer.
New tests, ran existing tests
> refactor: retention calculation into a new trait

- kernel/src/engine/ensure_data_types.rs
This PR relaxes type-checking rules to allow `LargeUtf8` conversion to `STRING` and `LargeBinary` conversion to `BINARY`. With this PR Delta kernel will allow committing arrow record batches that use `LargeUtf8` or that are built using `LargeStringBuilder` or corresponding types for building `LargeBinary`.
The main limitation that non-large variations of string and binary types impose is that they can hold up to 2 GBs of data, which makes it impossible to do kernel commits if there is a string or binary column larger than 2 GB. With this PR clients can just pass `RecordBatch` that uses `LargeUtf8` or `LargeBinary` as column types.
New UT
> feat: Allow LargeUTF8 -> String and LargeBinary -> Binary in arrow conversion

- acceptance/src/data.rs
- acceptance/src/meta.rs
- ffi/src/lib.rs
- ffi/src/transaction/mod.rs
- kernel/benches/metadata_bench.rs
- kernel/examples/common/src/lib.rs
- kernel/examples/inspect-table/src/main.rs
- kernel/examples/read-table-multi-threaded/src/main.rs
- kernel/examples/read-table-single-threaded/src/main.rs
- kernel/examples/write-table/src/main.rs
- kernel/src/actions/set_transaction.rs
- kernel/src/checkpoint/mod.rs
- kernel/src/checkpoint/tests.rs
- kernel/src/log_compaction/mod.rs
- kernel/src/log_compaction/tests.rs
- kernel/src/log_segment/tests.rs
- kernel/src/scan/mod.rs
- kernel/src/snapshot.rs
- kernel/src/snapshot/builder.rs
- kernel/src/table_changes/mod.rs
- kernel/tests/dv.rs
- kernel/tests/golden_tables.rs
- kernel/tests/hdfs.rs
- kernel/tests/read.rs
- kernel/tests/row_tracking.rs
- kernel/tests/v2_checkpoints.rs
- kernel/tests/write.rs
- test-utils/src/lib.rs
> [!IMPORTANT]
> This PR is split into two commits: (1) material changes, and (2) callsite updates
This PR integrates `Snapshot::try_new_from` into `SnapshotBuilder`. We move `Snapshot::try_new_from` into `Snapshot::builder_from` and modify `SnapshotBuilder` to return an `Arc<Snapshot>` instead of a `Snapshot`.
Also, `Snapshot::builder(table_root)` is renamed to `Snapshot::builder_for(table_root)`
1. Replaces `Snapshot::try_new_from(existing)` with `Snapshot::build_from(existing).build()`
2. `SnapshotBuilder::build()` now returns an `Arc<Snapshot>` instead of a `Snapshot`
3. Renames `Snapshot::builder` to `Snapshot::builder_for`
refactor, updated tests
> refactor!: migrate Snapshot::try_new_from into SnapshotBuilder

- kernel/src/action_reconciliation/log_replay.rs
- kernel/src/action_reconciliation/mod.rs
- kernel/src/checkpoint/mod.rs
- kernel/src/log_compaction/mod.rs
- kernel/src/log_compaction/writer.rs
- kernel/src/log_replay.rs
This is a followup from https://github.com/delta-io/delta-kernel-rs/pull/1234 and a pure refactoring change to:
Move the log replay for action reconciliation into the new `action_reconciliation` module
None - used internally by the checkpoint writer and the log compaction APIs with no behavioral or API changes
Existing tests
> refactor: move log replay into the action reconciliation module

- ffi/src/scan.rs
- kernel/examples/common/src/lib.rs
- kernel/examples/write-table/src/main.rs
- kernel/src/checkpoint/mod.rs
- kernel/src/lib.rs
- kernel/src/log_compaction/tests.rs
- kernel/src/log_compaction/writer.rs
- kernel/src/scan/mod.rs
- kernel/src/snapshot.rs
- kernel/src/snapshot/builder.rs
- kernel/src/table_changes/mod.rs
- kernel/src/transaction/mod.rs
introduce `SnapshotRef` type alias for `Arc<Snapshot>`
- Fixes https://github.com/delta-io/delta-kernel-rs/issues/1297
Existing tests.
> refactor: introduce SnapshotRef type alias

- kernel/src/actions/mod.rs
- kernel/src/row_tracking.rs
- kernel/src/transaction/mod.rs
This PR cleans up some nits as a follow-up to #1239.
Mostly refactoring. I added one more UT to verify the changes to the `RowTrackingVisitor`.
> refactor: Row tracking write cleanup

- ffi/src/engine_data.rs
- ffi/src/transaction/mod.rs
We were asking for a whole engine over ffi just to be able to convert the error. Let's just take an `AllocateErrorFn` instead.
in the ffi crate: `engine_data::get_engine_data` now takes an `AllocateErrorFn` instead of an engine.
Existing tests
> don't need a whole engine when converting into `ArrowEngineData`

- kernel/src/schema/mod.rs
#1287 extended the return type of `StructType::fields` with new traits that #1266 did not pick up for the newly introduced `StructType::into_fields`. This PR fixes that.
This PR extends the return type of the public API `StructType::into_fields`. Since we are only adding additional traits to the return type, all existing use cases should continue to work.
Refactoring only - existing tests verify correctness.
> chore!: Make StructType::into_fields return type consistent

- kernel/src/engine/arrow_utils.rs
- kernel/src/engine/default/parquet.rs
- kernel/src/engine/parquet_row_group_skipping.rs
- kernel/src/engine/sync/parquet.rs
- kernel/tests/read.rs
This PR follows up on #1266 and adds support for reading the row index metadata column to the default engine. The implementation directly follows the approach proposed in #920 and slightly modifies it to match the new metadata column API.
Quoting from #920 
> Deletion vectors (and row tracking, eventually) rely on accurate file-level row indexes. But they're not implemented in the kernel's default parquet reader. That means we must rely on the position of rows in data batches returned by each read, and we cannot apply optimizations such as stats-based row group skipping (see https://github.com/delta-io/delta-kernel-rs/issues/860).
>
> Add row index support to the default Parquet reader, in the form of a new RowIndex variant of ReorderIndexTransform. [...] The default parquet reader …
> feat!: Introduce row index metadata column

- ffi/src/scan.rs
Today we don't have a way to just visit all of a `CStringMap`. You rather have to probe one key at a time, and also somehow know all the keys ahead of time. This just allows visiting all the entries in one go.
New unit test
> feat: Add visit_string_map to the ffi

- kernel/src/actions/mod.rs
- kernel/src/lib.rs
- kernel/src/listed_log_files.rs
- kernel/src/log_path.rs
- kernel/src/log_segment.rs
- kernel/src/log_segment/tests.rs
- kernel/src/snapshot.rs
- kernel/src/snapshot/builder.rs
- kernel/src/table_changes/mod.rs
- kernel/tests/log_tail.rs
- test-utils/Cargo.toml
- test-utils/src/lib.rs
> [!NOTE]
> split into three commits (1 - material changes, 2 - callsites, 3 - test)
Two main things: (1) Adds `with_log_tail` API for to `SnapshotBuilder` (only for feature = `catalog-managed`) and (2) new `LogPath` type (and in a new module) to expose a public API for communicating delta log paths to kernel (currently leveraged in the new `with_log_tail` API).
This allows users (catalogs) to pass in a recent log_tail during snapshot construction. Note that our other high-level read API, `TableChanges` is not yet integrated for CCv2 (with log_tail during reads) and now explicitly checks that start/end snapshot are _not_ catalog-managed. Will track a follow up for CDF read support.
Removes the unnecessary `Snapshot::into_scan_builder` API - instead use `Snapshot::scan_builder`
New UT
> feat!(catalog-managed): add `log_tail` to `SnapshotBuilder`

- kernel/src/table_configuration.rs
https://github.com/delta-io/delta-kernel-rs/issues/1356
The in_commit_timestamp_enablement() method returns errors when ICT is enabled but enablement properties are missing, violating the Delta protocol. When table is created with ICT enablement info, the enablement properties will stay empty.
This change introduces a new enum to capture ICT enablement. 
New and edited unit tests
> fix: Change InCommitTimestamp enablement getter function 

- kernel/tests/log_compaction.rs
Add a new end to end test for tombstone expiration in log compaction writer we introduced in
https://github.com/delta-io/delta-kernel-rs/pull/1234
Fixes: https://github.com/delta-io/delta-kernel-rs/issues/1288
> test: Tombstone expiration e2e test for log compaction

- kernel/src/listed_log_files.rs
- kernel/src/log_segment.rs
- kernel/src/log_segment/tests.rs
- kernel/src/scan/mod.rs
- kernel/src/snapshot.rs
Add `latest_commit` field to `LogSegment` to prepare for in-commit timestamp (ICT) support. When ICT is enabled, we need access to the latest commit file to read timestamp information. We cannot depend on ascending commits because commits will be filtered out by checkpoint processing when checkpoint version equals commit version.
- Add `latest_commit_file: Option<ParsedLogPath>` field to `LogSegment` (optional)
- Add `latest_commit_file: Option<ParsedLogPath>` field to `ListedLogFiles` (optional)
- Track latest commit during listing, before any checkpoint filtering occurs
- Handle incremental snapshot updates by inheriting `latest_commit` from existing snapshot when new listing is empty
Added and changed tests to verify latest commit is passed through
> feat: Add latest_commit_file field to LogSegment

- kernel/examples/inspect-table/src/main.rs
We were hard coding the number of expected leaf fields we would get when visiting log data. This meant any changes to the log schema would silently break this example. We already have code to extract the offsets of the getters within the schema, so we should just adapt to changes (although reordering the schema would be bad).
This PR just computes the expected number of getters from the number of leaves in the schema, and ensures that's what we get back from the visitor, instead of hard-coding the number.
Run example on existing tables
> fix: be adaptive to the log schema changing in inspect-table

- acceptance/src/meta.rs
- ffi/src/lib.rs
- kernel/examples/inspect-table/src/main.rs
- kernel/src/scan/mod.rs
- kernel/src/snapshot.rs
- kernel/src/table_changes/mod.rs
- kernel/src/table_changes/scan.rs
- kernel/src/transaction/mod.rs
Fixes #648
This PR removes `Snapshot::metadata`, `Snapshot::protocol`, and `Snapshot::column_mapping_mode`. These are now all accessed through `snapshot.table_configuration`
> refactor!: Snapshot should not expose delta implementation details
