Cargo.toml, acceptance/Cargo.toml, derive-macros/Cargo.toml, ffi/Cargo.toml, kernel/Cargo.toml
Needed to add descriptions.
Also removed authors, it's not needed, and projects with many authors like this tend to leave it out.
=> really really ready to publish now

ffi/cffi-test.c
small fix since string isn't null terminated
=> Fix c-ffi test printing

NOTICE, ffi/src/lib.rs, kernel/examples/dump-table/src/main.rs, kernel/examples/read-table-multi-threaded/README.md, kernel/examples/read-table-multi-threaded/src/main.rs, kernel/src/error.rs, kernel/src/table.rs
Use the (slightly modified) code from [delta-rs](https://github.com/delta-io/delta-rs/blob/main/crates/core/src/table/builder.rs#L344) to handle parsing paths in a less surprising manner.
=> Better path parsing

.github/workflows/build.yml, ffi/cffi-test.c
note: not testing ffi on windows yet. added #214 to remind us to do that
=> use proper int type in c-ffi-test, and add ci to prevent issues in future

acceptance/Cargo.toml, ffi/Cargo.toml, kernel/Cargo.toml, kernel/examples/dump-table/Cargo.toml, kernel/examples/inspect-table/Cargo.toml, kernel/examples/read-table-multi-threaded/Cargo.toml
just updating arrow and some drive-by bumps.
=> chore: bump dependencies

Cargo.toml, README.md, ffi/Cargo.toml, kernel/Cargo.toml
=> Cut 0.1.0 (woo!)

kernel/examples/read-table-single-threaded/README.md, kernel/src/engine/arrow_conversion.rs
Add a README for the single threaded example
Fixes #238
=> Add readme for single-threaded, fix conversion bug

Cargo.toml, ffi/Cargo.toml, kernel/Cargo.toml
Updating for the arrow 0.52 support
=> update to version 0.1.1

.gitignore, ffi/src/lib.rs
=> Harmonise FFI error names

CHANGELOG.md, Cargo.toml, README.md, ffi/Cargo.toml, kernel/Cargo.toml
Doing another release 🍾 
(don't merge for me please, I need to adjust the date in the Changelog when I'm actually about to do the release)
=> prepare 0.2.0

kernel/src/lib.rs
=> fix inspect-table link in main docstring

kernel/src/engine/arrow_utils.rs
=> We were passing the wrong offset value when computing list offsets

.github/workflows/auto-assign-issue.yml
=> feat: add github action to self-assign the issue

kernel/src/expressions/scalars.rs
A perfectly good constant already existed -- use it!
=> [chore] Use chrono::UNIX_EPOCH instead of defining our own

ffi/src/handle.rs, kernel/examples/read-table-multi-threaded/Cargo.toml, kernel/examples/read-table-single-threaded/Cargo.toml
some quick fixes for both examples and a quick clippy fix for docstring
=> fix examples (and appease clippy)

CHANGELOG.md, Cargo.toml, ffi/Cargo.toml, kernel/Cargo.toml
release 0.4.1 which includes only #435
=> release 0.4.1

kernel/src/log_segment.rs, kernel/src/path.rs, kernel/src/snapshot.rs
Use `ParsedLogPath<FileMeta>`s instead of raw `FileMeta`s for `commit_files` and `checkpoint_files` fields in `LogSegment`.
Instead of
```rust
struct LogSegment {
commit_files: Vec<FileMeta>,
checkpoint_files: Vec<FileMeta>,
// ...
}
```
we now have
```rust
struct LogSegment {
commit_files: Vec<ParsedLogPath<FileMeta>>,
checkpoint_files: Vec<ParsedLogPath<FileMeta>>,
// ...
}
```
exisitng
=> use `ParsedLogPath`s for files in `LogSegment`

kernel/src/actions/mod.rs, kernel/src/engine/arrow_data.rs
new `protocol.reader_features()` and `protocol.writer_features()` getters. and added docs and visitor test.
=> implement table feature getters for `Protocol` and add test

kernel/src/actions/mod.rs, kernel/src/actions/visitors.rs, kernel/src/path.rs
This PR introduces the `Cdc` action and its associated `CdcVisitor`. This action is used for the Change Data Feed table feature.
- Ensure schema projection to `cdc` works
- Ensure that the visitor correctly extracts cdc actions.
- Ensure that metadata parses enableChangeDataFeed table feature.
=> Add `Cdc` action for Change Data Feed

CHANGELOG.md, Cargo.toml, README.md, ffi/Cargo.toml, kernel/Cargo.toml
alas automation didn't land yet. manual for now and will try to automate our next
=> release 0.5.0

kernel/src/engine/arrow_get_data.rs, kernel/src/engine/arrow_utils.rs, kernel/src/engine/parquet_row_group_skipping.rs, kernel/src/scan/log_replay.rs
new clippy landed - make the builds green
=> [chore] appease clippy in rustc 1.83

CHANGELOG.md
actual 0.6.0 release occurring now, ran into a build issue last friday which was fixed in #602
=> update changelog for actual 0.6.0 release

kernel/src/predicates/mod.rs
Somehow, the comparison operators were not implemented using inversion, even both their callers and callees were already inversion-aware. Fix it.
Existing unit tests cover this.
=> refactor: Simplify predicate evaluation by supporting inversion

kernel/src/actions/mod.rs
This PR introduces the `CheckpointMetadata` action.
This action is only allowed in checkpoints following [V2 spec](https://github.com/delta-io/delta/blob/master/PROTOCOL.md#v2-spec). For more information: [[link to protocol]](https://github.com/delta-io/delta/blob/master/PROTOCOL.md#checkpoint-metadata)
This PR is part of the on-going effort to implement single-file checkpoint write support. For reference, [[link to write API proposal]](https://github.com/delta-io/delta-kernel-rs/pull/779)
There already exists a `CheckpointMetadata` named struct [[link]](https://github.com/delta-io/delta-kernel-rs/blob/9290930bbeb1100e7af98c228dbd339eea38143a/kernel/src/snapshot.rs#L149) which represents the `_last_checkpoint` file. This PR renames this struct to `LastCheckpointHint`
- …
=> feat: add `CheckpointMetadata` action

kernel/src/engine/parquet_row_group_skipping.rs, kernel/src/expressions/mod.rs
The code for `Expression::references` uses an adhoc expression traversal instead of an expression transform, and the default parquet reader's `compute_field_indices` method uses an adhoc expression traversal instead of invoking `Expression::references`. Fix them both.
Existing unit tests.
=> refactor: Use ExpressionTransform instead of adhoc expression traversals

ffi/src/expressions/kernel.rs
The FFI `visit_expression_internal` function defines a bunch of nested helpers. Pull them out to top-level for better readability and maintainability.
Code movement only. Compilation suffices.
=> refactor: Code movement to tidy up ffi

kernel/src/expressions/mod.rs
Factor out some redundant code from impl Display for Expression and Predicate to a new helper function.
Code movement. Compilation suffices.
=> refactor: Simplify Display for Expression and Predicate

ffi/src/ffi_tracing.rs, kernel/src/expressions/transforms.rs, kernel/src/log_replay.rs
updates for new clippy. most interesting update was a new [`owned_cow`](https://rust-lang.github.io/rust-clippy/master/index.html#owned_cow) warning.
existing
=> fix: rustc 1.87 clippy fixes

kernel/src/kernel_predicates/mod.rs
Similar to #939, but for `KernelPredicateEvaluator` itself, not just `DataSkippingPredicateEvaluator` that relies on it. More preparation for opaque predicate support (for scalar evaluation of opaque predicates).
Existing unit tests plus a new compile-time check to verify dyn-compatibility.
=> refactor: Make KernelPredicateEvaluator trait dyn-compatible

kernel/src/expressions/transforms.rs, kernel/src/schema/mod.rs, kernel/src/utils.rs
Following up on
* https://github.com/delta-io/delta-kernel-rs/pull/1057
Expand `CowMapOwnedOrElse` with an impl for pairs of `Cow`, move it to utils.rs, and use it for schema transforms as well. 
Existing code covers this change.
=> refactor: Expand capability and usage of cow helper for transforms

kernel/src/engine/default/parquet.rs, kernel/src/schema/compare.rs, kernel/src/table_changes/log_replay.rs
title. update for rust 1.89
existing
=> chore: appease clippy in rustc 1.89

Cargo.toml, README.md, kernel/Cargo.toml, kernel/examples/read-table-multi-threaded/Cargo.toml, kernel/examples/read-table-single-threaded/Cargo.toml, kernel/src/arrow_compat.rs, kernel/src/checkpoint/tests.rs, kernel/src/engine/arrow_expression/mod.rs, kernel/src/engine/default/filesystem.rs, kernel/src/engine/default/json.rs, kernel/src/engine/default/parquet.rs, kernel/src/lib.rs
=> chore!: add arrow 56, drop arrow 54

kernel/src/log_compaction/mod.rs, kernel/src/log_compaction/tests.rs, kernel/src/log_compaction/writer.rs, kernel/src/snapshot.rs
Minor refactoring PR to incorporate the last review comments in https://github.com/delta-io/delta-kernel-rs/pull/1234
Updated tests.
=> refactor: Minor Refactoring in Log Compaction

ffi/src/ffi_test_utils.rs
Use this [link](https://github.com/delta-io/delta-kernel-rs/pull/1293/files) to review incremental changes.
- [**stack/improve_ok_or_panic**](https://github.com/delta-io/delta-kernel-rs/pull/1293) [[Files changed](https://github.com/delta-io/delta-kernel-rs/pull/1293/files)]
---------
=> chore: Add better panic message when not OK

kernel/src/actions/deletion_vector.rs, kernel/src/actions/visitors.rs, kernel/src/table_changes/log_replay/tests.rs, kernel/src/table_changes/resolve_dvs.rs, kernel/src/table_changes/scan_file.rs
I've been playing around with the Deletion Vectors, and I thought it would be a nice touch to convert the string to an enum. This makes the code more readable and avoids the catch-all branch in the pattern matching.
Existing tests.
=> feat: Convert DV `storage_type` to enum
